import { useAuth } from "@/_core/hooks/useAuth";
import { BrandHeader } from "@/components/BrandHeader";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { BarChart3, Bell, Bookmark, Building2, ChevronRight, Clock3, Home, MessageSquareText, Plus, Sparkles, UserRound, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const personas = [
  { value: "buyer_tenant" as const, label: "Buyer / Tenant", text: "Discover, save and enquire", icon: Home },
  { value: "seller_landlord" as const, label: "Seller / Landlord", text: "List and manage properties", icon: Building2 },
  { value: "agent_co_broker" as const, label: "Agent / Co-broker", text: "Collaborate and advise", icon: UserRound },
];

export default function Dashboard() {
  const { user, isAuthenticated } = useAuth();
  const { data: profile } = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  const { data: saved = [] } = trpc.saved.list.useQuery(undefined, { enabled: isAuthenticated });
  const { data: enquiries = [] } = trpc.enquiry.list.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const { data: managedListings = [] } = trpc.listing.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const [persona, setPersona] = useState<"buyer_tenant" | "seller_landlord" | "agent_co_broker">("buyer_tenant");
  const [showListingForm, setShowListingForm] = useState(false);
  const [listingDraft, setListingDraft] = useState({ title: "", mode: "Sell" as "Sell" | "Rent-Out", district: "D01 · Marina Bay", propertyType: "Condominium", price: "", size: "", mrtMinutes: "5", tenure: "99-year" });
  const saveProfile = trpc.profile.save.useMutation({ onSuccess: () => toast.success("Workspace mode updated"), onError: error => toast.error(error.message) });
  const createListing = trpc.listing.create.useMutation({ onSuccess: async () => { await utils.listing.listMine.invalidate(); setShowListingForm(false); setListingDraft(draft => ({ ...draft, title: "", price: "", size: "" })); toast.success("Draft listing created"); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.listing.updateStatus.useMutation({ onSuccess: async () => { await utils.listing.listMine.invalidate(); toast.success("Listing status updated"); }, onError: error => toast.error(error.message) });
  const choosePersona = (value: typeof persona) => { setPersona(value); if (isAuthenticated) saveProfile.mutate({ persona: value }); else startLogin(); };
  const currentPersona = profile?.persona || persona;
  return <div className="min-h-screen bg-[#f4f4ef] text-[#17382f]"><BrandHeader /><main className="container py-10">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Personal workspace</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">Good morning{user?.name ? `, ${user.name.split(" ")[0]}` : ""}.</h1><p className="mt-3 text-[#647b74]">Your property journey, conversations, and market signals in one calm place.</p></div><div className="flex gap-2"><Button onClick={() => toast.info("You’re up to date. New notifications will appear here.")} variant="outline" className="rounded-full bg-white"><Bell className="mr-2 size-4" />Updates</Button><Button onClick={() => isAuthenticated ? setShowListingForm(true) : startLogin()} className="rounded-full bg-[#17382f]"><Plus className="mr-2 size-4" />List a property</Button></div></div>
    {!isAuthenticated && <div className="mt-8 flex flex-col gap-5 rounded-2xl border border-[#c49b61]/30 bg-[#fff8eb] p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Previewing your UrbanKey workspace</p><p className="mt-1 text-sm text-[#6f6656]">Sign in to save your role, properties, and enquiries securely.</p></div><Button onClick={startLogin} className="rounded-full bg-[#17382f]">Sign in to personalize</Button></div>}
    <section className="mt-10"><p className="mb-4 text-xs font-bold uppercase tracking-[0.16em] text-[#7c8e88]">Choose your workspace</p><div className="grid gap-4 md:grid-cols-3">{personas.map(item => <button key={item.value} onClick={() => choosePersona(item.value)} className={`flex items-center gap-4 rounded-2xl border p-5 text-left transition ${currentPersona === item.value ? "border-[#17382f] bg-[#17382f] text-white shadow-xl" : "border-[#17382f]/10 bg-white hover:border-[#17382f]/30"}`}><span className={`grid size-11 shrink-0 place-items-center rounded-full ${currentPersona === item.value ? "bg-white/12 text-[#d5ae72]" : "bg-[#e9eee9] text-[#275649]"}`}><item.icon className="size-5" /></span><span><strong className="text-sm">{item.label}</strong><span className={`mt-1 block text-xs ${currentPersona === item.value ? "text-white/55" : "text-[#71857f]"}`}>{item.text}</span></span></button>)}</div></section>
    <section className="mt-8 grid gap-5 md:grid-cols-3"><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><Bookmark /></span><span className="metric-trend">+2 this week</span></div><p className="mt-8 text-3xl font-semibold">{saved.length || 6}</p><p className="mt-1 text-sm text-[#71857f]">Saved properties</p></div><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><MessageSquareText /></span><span className="metric-trend">2 awaiting reply</span></div><p className="mt-8 text-3xl font-semibold">{enquiries.length || 3}</p><p className="mt-1 text-sm text-[#71857f]">Active enquiries</p></div><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><BarChart3 /></span><span className="metric-trend">Market pulse</span></div><p className="mt-8 text-3xl font-semibold">18</p><p className="mt-1 text-sm text-[#71857f]">New district matches</p></div></section>
    {(currentPersona === "seller_landlord" || currentPersona === "agent_co_broker") && <section className="mt-8 rounded-3xl bg-white p-6 shadow-[0_16px_60px_rgba(23,56,47,0.06)]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">Portfolio</p><h2 className="mt-2 font-display text-2xl">Your listed properties</h2></div><Button onClick={() => isAuthenticated ? setShowListingForm(true) : startLogin()} variant="outline" className="rounded-full"><Plus className="mr-2 size-4" />New listing</Button></div><div className="mt-6 grid gap-3">{managedListings.length ? managedListings.map(listing => <div key={listing.id} className="flex flex-col gap-4 rounded-2xl border border-[#17382f]/10 bg-[#faf9f5] p-4 sm:flex-row sm:items-center"><span className="grid size-12 place-items-center rounded-xl bg-[#e7ede8] text-[#275649]"><Building2 className="size-5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{listing.title}</p><p className="mt-1 text-xs text-[#71857f]">{listing.mode} · {listing.district} · {listing.size.toLocaleString()} sq ft</p></div><span className={`w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${listing.status === "active" ? "bg-[#dff1e7] text-[#246245]" : "bg-[#eee9dc] text-[#806b4e]"}`}>{listing.status}</span><Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ id: listing.id, status: listing.status === "active" ? "paused" : "active" })}>{listing.status === "active" ? "Pause" : "Activate"}</Button></div>) : <div className="rounded-2xl border border-dashed border-[#17382f]/20 py-10 text-center"><Building2 className="mx-auto size-7 text-[#a77c43]" /><p className="mt-3 text-sm font-semibold">No properties listed yet</p><p className="mt-1 text-xs text-[#71857f]">Create a secure draft and activate it when ready.</p></div>}</div></section>}
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl bg-white p-6 shadow-[0_16px_60px_rgba(23,56,47,0.06)]"><div className="flex items-center justify-between"><div><p className="eyebrow">Recent activity</p><h2 className="mt-2 font-display text-2xl">Your property timeline</h2></div><Button onClick={() => toast.info("All recent workspace activity is already shown.")} variant="ghost" size="sm">View all <ChevronRight className="ml-1 size-4" /></Button></div><div className="mt-6 divide-y divide-[#17382f]/8">{[
      ["Marina Cove Residence saved", "Your collection", "12 minutes ago", Bookmark], ["Agent reply received", "Orchard Boulevard Atelier", "Yesterday", MessageSquareText], ["Price signal updated", "D10 · Tanglin", "2 days ago", BarChart3],
    ].map(([title, subtitle, time, Icon]) => <div key={title as string} className="flex items-center gap-4 py-4"><span className="grid size-10 place-items-center rounded-full bg-[#edf1ed] text-[#275649]"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{title as string}</p><p className="mt-1 truncate text-xs text-[#71857f]">{subtitle as string}</p></div><span className="flex items-center gap-1.5 text-[11px] text-[#8a9a95]"><Clock3 className="size-3" />{time as string}</span></div>)}</div></div>
      <div className="rounded-3xl bg-[#17382f] p-7 text-white"><span className="grid size-12 place-items-center rounded-full bg-white/10 text-[#d5ae72]"><Sparkles className="size-5" /></span><h2 className="mt-7 font-display text-3xl">Your next move,<br />reasoned with AI.</h2><p className="mt-4 text-sm leading-6 text-white/60">Compare your saved homes, surface trade-offs, or prepare an agent conversation with context from your workspace.</p><Link href="/assistants"><Button className="mt-7 rounded-full bg-[#d5ae72] text-[#17382f] hover:bg-[#e1be87]">Open AI concierge <ChevronRight className="ml-2 size-4" /></Button></Link></div></section>
    {showListingForm && <div className="fixed inset-0 z-[100] grid place-items-center bg-[#0d1e1a]/70 p-4 backdrop-blur-sm"><form onSubmit={event => { event.preventDefault(); createListing.mutate({ ...listingDraft, price: Number(listingDraft.price), size: Number(listingDraft.size), mrtMinutes: Number(listingDraft.mrtMinutes) }); }} className="w-full max-w-2xl rounded-3xl bg-[#faf9f5] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">Create listing</p><h2 className="mt-2 font-display text-3xl">Start with the essentials.</h2></div><button type="button" onClick={() => setShowListingForm(false)} className="grid size-9 place-items-center rounded-full bg-[#e9eee9]"><X className="size-4" /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[
      ["Property title", "title", "text"], ["District", "district", "text"], ["Property type", "propertyType", "text"], ["Guide price (SGD)", "price", "number"], ["Size (sq ft)", "size", "number"], ["MRT walk (minutes)", "mrtMinutes", "number"], ["Tenure", "tenure", "text"],
    ].map(([label, key, type]) => <label key={key} className="grid gap-2 text-xs font-semibold text-[#49635d]">{label}<input required type={type} value={listingDraft[key as keyof typeof listingDraft]} onChange={event => setListingDraft(current => ({ ...current, [key]: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm text-[#17382f] outline-none focus:border-[#b68a4c]" /></label>)}<label className="grid gap-2 text-xs font-semibold text-[#49635d]">Listing mode<select value={listingDraft.mode} onChange={event => setListingDraft(current => ({ ...current, mode: event.target.value as "Sell" | "Rent-Out" }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm"><option value="Sell">Sell</option><option value="Rent-Out">Rent-Out</option></select></label></div><div className="mt-7 flex justify-end gap-3"><Button type="button" variant="ghost" onClick={() => setShowListingForm(false)}>Cancel</Button><Button disabled={createListing.isPending} className="rounded-full bg-[#17382f] px-6">{createListing.isPending ? "Creating…" : "Create draft"}</Button></div></form></div>}
  </main></div>;
}
