import { useAuth } from "@/_core/hooks/useAuth";
import { BrandHeader } from "@/components/BrandHeader";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useMarket } from "@/contexts/MarketContext";
import { trpc } from "@/lib/trpc";
import { formatMarketCurrency } from "@shared/marketConfig";
import { commercialPropertyTypes, propertyTypes } from "@shared/propertyData";
import { BarChart3, Bell, Bookmark, Building2, ChevronRight, Clock3, Home, MessageSquareText, Plus, Sparkles, UserRound, Warehouse, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const personas = [
  { value: "buyer_tenant" as const, label: "Buyer / Tenant", text: "Discover, save and enquire", icon: Home },
  { value: "seller_landlord" as const, label: "Seller / Landlord", text: "List and manage properties", icon: Building2 },
  { value: "agent_co_broker" as const, label: "Agent / Co-broker", text: "Collaborate and advise", icon: UserRound },
];

export default function Dashboard() {
  const { user, isAuthenticated } = useAuth();
  const { market } = useMarket();
  const { data: profile } = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  const { data: saved = [] } = trpc.saved.list.useQuery(undefined, { enabled: isAuthenticated });
  const { data: enquiries = [] } = trpc.enquiry.list.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const managedListingQuery = useMemo(() => ({ marketId: market.id }), [market.id]);
  const { data: managedListings = [] } = trpc.listing.listMine.useQuery(managedListingQuery, { enabled: isAuthenticated });
  const [persona, setPersona] = useState<"buyer_tenant" | "seller_landlord" | "agent_co_broker">("buyer_tenant");
  const [showListingForm, setShowListingForm] = useState(false);
  const [listingDraft, setListingDraft] = useState({ title: "", mode: "Sell" as "Sell" | "Rent-Out", district: market.geography.regions[0] ?? "", propertyType: "Condominium", price: "", size: "", mrtMinutes: "5", tenure: "99-year", commercialUsage: "", floorLoading: "", ceilingHeight: "", loadingAccess: "", parkingLots: "", availableFrom: "" });
  const saveProfile = trpc.profile.save.useMutation({ onSuccess: () => toast.success("Workspace mode updated"), onError: error => toast.error(error.message) });
  const createListing = trpc.listing.create.useMutation({ onSuccess: async () => { await utils.listing.listMine.invalidate(); setShowListingForm(false); setListingDraft(draft => ({ ...draft, title: "", price: "", size: "" })); toast.success("Draft listing created"); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.listing.updateStatus.useMutation({ onSuccess: async () => { await utils.listing.listMine.invalidate(); toast.success("Listing status updated"); }, onError: error => toast.error(error.message) });
  const choosePersona = (value: typeof persona) => { setPersona(value); if (isAuthenticated) saveProfile.mutate({ persona: value }); else startLogin(); };
  const currentPersona = profile?.persona || persona;
  const commercialDraft = commercialPropertyTypes.includes(listingDraft.propertyType as (typeof commercialPropertyTypes)[number]);
  const openListingForm = () => {
    setListingDraft(draft => ({ ...draft, district: market.geography.regions.includes(draft.district) ? draft.district : market.geography.regions[0] ?? "" }));
    setShowListingForm(true);
  };
  const submitListing = () => createListing.mutate({
    marketId: market.id,
    title: listingDraft.title,
    mode: listingDraft.mode,
    district: listingDraft.district,
    propertyType: listingDraft.propertyType,
    price: Number(listingDraft.price),
    size: Number(listingDraft.size),
    mrtMinutes: Number(listingDraft.mrtMinutes),
    tenure: listingDraft.tenure,
    ...(commercialDraft ? {
      commercialUsage: listingDraft.commercialUsage || undefined,
      floorLoading: listingDraft.floorLoading ? Number(listingDraft.floorLoading) : undefined,
      ceilingHeight: listingDraft.ceilingHeight ? Number(listingDraft.ceilingHeight) : undefined,
      loadingAccess: listingDraft.loadingAccess || undefined,
      parkingLots: listingDraft.parkingLots ? Number(listingDraft.parkingLots) : undefined,
      availableFrom: listingDraft.availableFrom || undefined,
    } : {}),
  });
  return <div className="min-h-screen bg-[#f4f4ef] text-[#17382f]"><BrandHeader /><main className="container py-10">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Personal workspace · {market.countryName}</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">Good morning{user?.name ? `, ${user.name.split(" ")[0]}` : ""}.</h1><p className="mt-3 text-[#647b74]">Your property journey, conversations, and market signals in one calm place.</p></div><div className="flex gap-2"><Button onClick={() => toast.info("You’re up to date. New notifications will appear here.")} variant="outline" className="rounded-full bg-white"><Bell className="mr-2 size-4" />Updates</Button><Button onClick={() => isAuthenticated ? openListingForm() : startLogin()} className="rounded-full bg-[#17382f]"><Plus className="mr-2 size-4" />List a property</Button></div></div>
    {!isAuthenticated && <div className="mt-8 flex flex-col gap-5 rounded-2xl border border-[#c49b61]/30 bg-[#fff8eb] p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Previewing your UrbanKey workspace</p><p className="mt-1 text-sm text-[#6f6656]">Sign in to save your role, properties, and enquiries securely.</p></div><Button onClick={startLogin} className="rounded-full bg-[#17382f]">Sign in to personalize</Button></div>}
    <section className="mt-10"><p className="mb-4 text-xs font-bold uppercase tracking-[0.16em] text-[#7c8e88]">Choose your workspace</p><div className="grid gap-4 md:grid-cols-3">{personas.map(item => <button key={item.value} onClick={() => choosePersona(item.value)} className={`flex items-center gap-4 rounded-2xl border p-5 text-left transition ${currentPersona === item.value ? "border-[#17382f] bg-[#17382f] text-white shadow-xl" : "border-[#17382f]/10 bg-white hover:border-[#17382f]/30"}`}><span className={`grid size-11 shrink-0 place-items-center rounded-full ${currentPersona === item.value ? "bg-white/12 text-[#d5ae72]" : "bg-[#e9eee9] text-[#275649]"}`}><item.icon className="size-5" /></span><span><strong className="text-sm">{item.label}</strong><span className={`mt-1 block text-xs ${currentPersona === item.value ? "text-white/55" : "text-[#71857f]"}`}>{item.text}</span></span></button>)}</div></section>
    <section className="mt-8 grid gap-5 md:grid-cols-3"><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><Bookmark /></span><span className="metric-trend">+2 this week</span></div><p className="mt-8 text-3xl font-semibold">{saved.length || 6}</p><p className="mt-1 text-sm text-[#71857f]">Saved properties</p></div><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><MessageSquareText /></span><span className="metric-trend">2 awaiting reply</span></div><p className="mt-8 text-3xl font-semibold">{enquiries.length || 3}</p><p className="mt-1 text-sm text-[#71857f]">Active enquiries</p></div><div className="metric-card"><div className="flex items-center justify-between"><span className="metric-icon"><BarChart3 /></span><span className="metric-trend">Market pulse</span></div><p className="mt-8 text-3xl font-semibold">18</p><p className="mt-1 text-sm text-[#71857f]">New {market.geography.regionLabel.toLowerCase()} matches</p></div></section>
    {(currentPersona === "seller_landlord" || currentPersona === "agent_co_broker") && <section className="mt-8 rounded-3xl bg-white p-6 shadow-[0_16px_60px_rgba(23,56,47,0.06)]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="eyebrow">Portfolio · {market.countryName}</p><h2 className="mt-2 font-display text-2xl">Your listed properties</h2></div><Button onClick={() => isAuthenticated ? openListingForm() : startLogin()} variant="outline" className="rounded-full"><Plus className="mr-2 size-4" />New listing</Button></div><div className="mt-6 grid gap-3">{managedListings.length ? managedListings.map(listing => <div key={listing.id} className="flex flex-col gap-4 rounded-2xl border border-[#17382f]/10 bg-[#faf9f5] p-4 sm:flex-row sm:items-center"><span className="grid size-12 place-items-center rounded-xl bg-[#e7ede8] text-[#275649]">{commercialPropertyTypes.includes(listing.propertyType as (typeof commercialPropertyTypes)[number]) ? <Warehouse className="size-5" /> : <Building2 className="size-5" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{listing.title}</p><p className="mt-1 text-xs text-[#71857f]">{listing.mode} · {listing.propertyType} · {listing.district} · {listing.size.toLocaleString(market.locale)} {market.terminology.areaUnit}</p>{listing.commercialUsage && <p className="mt-1 truncate text-[11px] font-medium text-[#8b6b3d]">{listing.commercialUsage}{listing.floorLoading ? ` · ${listing.floorLoading} kN/m²` : ""}{listing.ceilingHeight ? ` · ${listing.ceilingHeight} m clear` : ""}</p>}</div><span className="rounded-full bg-[#edf1ed] px-3 py-1 text-[10px] font-semibold text-[#49635d]">{formatMarketCurrency(listing.price, market)}{listing.mode === "Rent-Out" ? "/mo" : ""}</span><span className={`w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${listing.status === "active" ? "bg-[#dff1e7] text-[#246245]" : "bg-[#eee9dc] text-[#806b4e]"}`}>{listing.status}</span><Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ id: listing.id, status: listing.status === "active" ? "paused" : "active" })}>{listing.status === "active" ? "Pause" : "Activate"}</Button></div>) : <div className="rounded-2xl border border-dashed border-[#17382f]/20 py-10 text-center"><Building2 className="mx-auto size-7 text-[#a77c43]" /><p className="mt-3 text-sm font-semibold">No properties listed yet</p><p className="mt-1 text-xs text-[#71857f]">Create a secure draft for the {market.countryName} market and activate it when ready.</p></div>}</div></section>}
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl bg-white p-6 shadow-[0_16px_60px_rgba(23,56,47,0.06)]"><div className="flex items-center justify-between"><div><p className="eyebrow">Recent activity</p><h2 className="mt-2 font-display text-2xl">Your property timeline</h2></div><Button onClick={() => toast.info("All recent workspace activity is already shown.")} variant="ghost" size="sm">View all <ChevronRight className="ml-1 size-4" /></Button></div><div className="mt-6 divide-y divide-[#17382f]/8">{[
      ["Marina Cove Residence saved", "Your collection", "12 minutes ago", Bookmark], ["Agent reply received", "Orchard Boulevard Atelier", "Yesterday", MessageSquareText], ["Price signal updated", "D10 · Tanglin", "2 days ago", BarChart3],
    ].map(([title, subtitle, time, Icon]) => <div key={title as string} className="flex items-center gap-4 py-4"><span className="grid size-10 place-items-center rounded-full bg-[#edf1ed] text-[#275649]"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{title as string}</p><p className="mt-1 truncate text-xs text-[#71857f]">{subtitle as string}</p></div><span className="flex items-center gap-1.5 text-[11px] text-[#8a9a95]"><Clock3 className="size-3" />{time as string}</span></div>)}</div></div>
      <div className="rounded-3xl bg-[#17382f] p-7 text-white"><span className="grid size-12 place-items-center rounded-full bg-white/10 text-[#d5ae72]"><Sparkles className="size-5" /></span><h2 className="mt-7 font-display text-3xl">Your next move,<br />reasoned with AI.</h2><p className="mt-4 text-sm leading-6 text-white/60">Compare saved homes or commercial assets, surface operational trade-offs, and prepare a well-contextualized agent conversation.</p><Link href="/assistants"><Button className="mt-7 rounded-full bg-[#d5ae72] text-[#17382f] hover:bg-[#e1be87]">Open AI concierge <ChevronRight className="ml-2 size-4" /></Button></Link></div></section>
    {showListingForm && <div className="fixed inset-0 z-[100] grid place-items-center overflow-y-auto bg-[#0d1e1a]/70 p-4 backdrop-blur-sm"><form onSubmit={event => { event.preventDefault(); submitListing(); }} className="my-4 max-h-[calc(100vh-2rem)] w-full max-w-3xl overflow-y-auto rounded-3xl bg-[#faf9f5] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">Create listing</p><h2 className="mt-2 font-display text-3xl">Capture the asset essentials.</h2></div><button type="button" aria-label="Close listing form" onClick={() => setShowListingForm(false)} className="grid size-9 place-items-center rounded-full bg-[#e9eee9]"><X className="size-4" /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Property title<input required value={listingDraft.title} onChange={event => setListingDraft(current => ({ ...current, title: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm text-[#17382f] outline-none focus:border-[#b68a4c]" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Listing mode<select value={listingDraft.mode} onChange={event => setListingDraft(current => ({ ...current, mode: event.target.value as "Sell" | "Rent-Out" }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm"><option value="Sell">Sell</option><option value="Rent-Out">Rent-Out</option></select></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">{market.geography.regionLabel}{market.geography.regions.length ? <select value={listingDraft.district} onChange={event => setListingDraft(current => ({ ...current, district: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm">{market.geography.regions.map(item => <option key={item} value={item}>{item}</option>)}</select> : <input required value={listingDraft.district} onChange={event => setListingDraft(current => ({ ...current, district: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" placeholder={`Enter ${market.geography.regionLabel.toLowerCase()}`} />}</label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Property type<select value={listingDraft.propertyType} onChange={event => setListingDraft(current => ({ ...current, propertyType: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm">{propertyTypes.map(item => <option key={item} value={item}>{item}</option>)}</select></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">{listingDraft.mode === "Rent-Out" ? `Guide monthly rent (${market.currency})` : `Guide price (${market.currency})`}<input required min="1" type="number" value={listingDraft.price} onChange={event => setListingDraft(current => ({ ...current, price: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Size ({market.terminology.areaUnit})<input required min="1" type="number" value={listingDraft.size} onChange={event => setListingDraft(current => ({ ...current, size: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">{market.terminology.transit} walk / travel (minutes)<input required min="0" max="60" type="number" value={listingDraft.mrtMinutes} onChange={event => setListingDraft(current => ({ ...current, mrtMinutes: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Ownership<select value={listingDraft.tenure} onChange={event => setListingDraft(current => ({ ...current, tenure: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm"><option>Freehold</option><option>999-year</option><option>99-year</option><option>60-year</option><option>30-year</option></select></label>
      {commercialDraft && <><div className="sm:col-span-2 mt-2 rounded-xl bg-[#f0eadf] px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#76552f]">Commercial and industrial specifications</p><p className="mt-1 text-xs text-[#647b74]">These operational fields help buyers and tenants assess suitability before due diligence.</p></div>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Approved / intended usage<input required value={listingDraft.commercialUsage} onChange={event => setListingDraft(current => ({ ...current, commercialUsage: event.target.value }))} placeholder="Office, retail, warehouse, food factory…" className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Available from<input type="date" value={listingDraft.availableFrom} onChange={event => setListingDraft(current => ({ ...current, availableFrom: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Floor loading (kN/m²)<input min="0.1" step="0.1" type="number" value={listingDraft.floorLoading} onChange={event => setListingDraft(current => ({ ...current, floorLoading: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Ceiling height (m)<input min="0.1" step="0.1" type="number" value={listingDraft.ceilingHeight} onChange={event => setListingDraft(current => ({ ...current, ceilingHeight: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Loading access<input value={listingDraft.loadingAccess} onChange={event => setListingDraft(current => ({ ...current, loadingAccess: event.target.value }))} placeholder="40-ft container, dock leveller…" className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label>
      <label className="grid gap-2 text-xs font-semibold text-[#49635d]">Parking lots<input min="0" type="number" value={listingDraft.parkingLots} onChange={event => setListingDraft(current => ({ ...current, parkingLots: event.target.value }))} className="h-11 rounded-xl border border-[#17382f]/12 bg-white px-3 text-sm" /></label></>}
      </div><div className="mt-7 flex justify-end gap-3"><Button type="button" variant="ghost" onClick={() => setShowListingForm(false)}>Cancel</Button><Button disabled={createListing.isPending} className="rounded-full bg-[#17382f] px-6">{createListing.isPending ? "Creating…" : "Create draft"}</Button></div></form></div>}
  </main></div>;
}
