import { BrandHeader } from "@/components/BrandHeader";
import { PropertyCard } from "@/components/PropertyCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLanguage } from "@/contexts/LanguageContext";
import { useMarket } from "@/contexts/MarketContext";
import { trpc } from "@/lib/trpc";
import { formatMarketCurrency, getAllRegionsLabel } from "@shared/marketConfig";
import { commercialPropertyTypes, propertyTypes } from "@shared/propertyData";
import { Filter, ListFilter, Map, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const readQuery = () => new URLSearchParams(window.location.search);

export default function Explore() {
  const { market } = useMarket();
  const { t } = useLanguage();
  const allRegionsLabel = getAllRegionsLabel(market);
  const modeLabels = { Buy: t("nav.buy"), Rent: t("nav.rent"), Sell: t("nav.sell"), "Rent-Out": t("nav.rentOut") } as const;
  const params = useMemo(readQuery, []);
  const [mode, setMode] = useState(params.get("mode") || "Buy");
  const [search, setSearch] = useState(params.get("search") || "");
  const [district, setDistrict] = useState(params.get("district") || allRegionsLabel);
  const [propertyType, setPropertyType] = useState(params.get("propertyType") || "All types");
  const [tenure, setTenure] = useState(params.get("tenure") || "Any ownership");
  const [maxPrice, setMaxPrice] = useState(params.get("maxPrice") || "Any price");
  const [minSize, setMinSize] = useState(params.get("minSize") || "Any size");
  const [mrtWalk, setMrtWalk] = useState(params.get("maxMrtMinutes") || "Any distance");
  const [commercialUsage, setCommercialUsage] = useState(params.get("commercialUsage") || "Any usage");
  const [minFloorLoading, setMinFloorLoading] = useState(params.get("minFloorLoading") || "Any loading");
  const [minCeilingHeight, setMinCeilingHeight] = useState(params.get("minCeilingHeight") || "Any height");
  const commercialFocus = propertyType === "All types" || commercialPropertyTypes.includes(propertyType as (typeof commercialPropertyTypes)[number]);
  useEffect(() => {
    setDistrict(allRegionsLabel);
    setTenure("Any ownership");
  }, [allRegionsLabel]);
  const queryInput = useMemo(() => ({ marketId: market.id, mode: mode as "Buy" | "Sell" | "Rent" | "Rent-Out", search: search || undefined, district, propertyType, tenure: tenure.startsWith("Any ") ? undefined : tenure, maxPrice: maxPrice === "Any price" ? undefined : Number(maxPrice), minSize: minSize === "Any size" ? undefined : Number(minSize), maxMrtMinutes: mrtWalk === "Any distance" ? undefined : Number(mrtWalk), commercialUsage: commercialUsage === "Any usage" ? undefined : commercialUsage, minFloorLoading: minFloorLoading === "Any loading" ? undefined : Number(minFloorLoading), minCeilingHeight: minCeilingHeight === "Any height" ? undefined : Number(minCeilingHeight) }), [market.id, mode, search, district, propertyType, tenure, maxPrice, minSize, mrtWalk, commercialUsage, minFloorLoading, minCeilingHeight]);
  const { data: properties = [], isLoading } = trpc.property.list.useQuery(queryInput);
  return <div className="min-h-screen bg-[#f5f4ef] text-[#17382f]"><BrandHeader />
    <main>
      <section className="border-b border-[#17382f]/10 bg-[#faf9f5] py-10"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{t("explore.discover", { country: market.countryName })}</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">{t("explore.title")}</h1></div><Link href="/map"><Button className="rounded-full bg-[#17382f]"><Map className="mr-2 size-4" />{t("explore.onMap")}</Button></Link></div>
        <div className="mt-8 grid gap-3 rounded-2xl border border-[#17382f]/10 bg-white p-3 shadow-sm md:grid-cols-2 xl:grid-cols-[1.4fr_repeat(6,1fr)]"><div className="flex items-center gap-2 rounded-xl bg-[#f0f2ee] px-3"><Search className="size-4 text-[#9b7440]" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder={t("explore.search", { transit: market.terminology.transit, region: market.geography.regionLabel.toLowerCase() })} className="border-0 bg-transparent px-0 shadow-none focus-visible:ring-0" /></div>
          <Select value={mode} onValueChange={setMode}><SelectTrigger aria-label={t("explore.listingMode")} className="border-0 bg-[#f0f2ee] shadow-none"><span>{modeLabels[mode as keyof typeof modeLabels] ?? mode}</span></SelectTrigger><SelectContent><SelectItem value="Buy">{modeLabels.Buy}</SelectItem><SelectItem value="Rent">{modeLabels.Rent}</SelectItem><SelectItem value="Sell">{modeLabels.Sell}</SelectItem><SelectItem value="Rent-Out">{modeLabels["Rent-Out"]}</SelectItem></SelectContent></Select>
          <Select value={district} onValueChange={setDistrict}><SelectTrigger aria-label={market.geography.regionLabel} className="border-0 bg-[#f0f2ee] shadow-none"><span className="truncate">{district === allRegionsLabel ? t("explore.allRegions", { region: market.geography.regionLabel }) : district}</span></SelectTrigger><SelectContent>{[allRegionsLabel, ...market.geography.regions].map(item => <SelectItem key={item} value={item}>{item === allRegionsLabel ? t("explore.allRegions", { region: market.geography.regionLabel }) : item}</SelectItem>)}</SelectContent></Select>
          <Select value={propertyType} onValueChange={setPropertyType}><SelectTrigger aria-label={t("explore.propertyType")} className="border-0 bg-[#f0f2ee] shadow-none"><span>{propertyType === "All types" ? t("explore.allTypes") : propertyType}</span></SelectTrigger><SelectContent><SelectItem value="All types">{t("explore.allTypes")}</SelectItem>{propertyTypes.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select>
          <Select value={tenure} onValueChange={setTenure}><SelectTrigger aria-label={t("explore.anyOwnership")} className="border-0 bg-[#f0f2ee] shadow-none"><span>{tenure === "Any ownership" ? t("explore.anyOwnership") : tenure}</span></SelectTrigger><SelectContent><SelectItem value="Any ownership">{t("explore.anyOwnership")}</SelectItem><SelectItem value="Freehold">Freehold</SelectItem><SelectItem value="99-year">99-year</SelectItem><SelectItem value="60-year">60-year</SelectItem><SelectItem value="30-year">30-year</SelectItem></SelectContent></Select>
          <Select value={minSize} onValueChange={setMinSize}><SelectTrigger aria-label={t("explore.minArea")} className="border-0 bg-[#f0f2ee] shadow-none"><span>{minSize === "Any size" ? t("explore.anySize") : `${Number(minSize).toLocaleString(market.locale)}+ ${market.terminology.areaUnit}`}</span></SelectTrigger><SelectContent><SelectItem value="Any size">{t("explore.anySize")}</SelectItem>{[1000, 5000, 20000, 50000].map(value => <SelectItem key={value} value={String(value)}>{value.toLocaleString(market.locale)}+ {market.terminology.areaUnit}</SelectItem>)}</SelectContent></Select>
          <Select value={mrtWalk} onValueChange={setMrtWalk}><SelectTrigger aria-label={t("explore.anyTravel", { transit: market.terminology.transit })} className="border-0 bg-[#f0f2ee] shadow-none"><span>{mrtWalk === "Any distance" ? t("explore.anyTravel", { transit: market.terminology.transit }) : t("explore.within", { minutes: mrtWalk })}</span></SelectTrigger><SelectContent><SelectItem value="Any distance">{t("explore.anyTravel", { transit: market.terminology.transit })}</SelectItem>{[5, 10, 15].map(value => <SelectItem key={value} value={String(value)}>{t("explore.within", { minutes: value })}</SelectItem>)}</SelectContent></Select>
        </div>{commercialFocus && <div className="mt-3 grid gap-3 rounded-2xl border border-[#a77c43]/20 bg-[#f4efe4] p-3 sm:grid-cols-3"><div className="px-2 py-1"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#76552f]">{t("explore.commercial")}</p><p className="mt-1 text-xs text-[#647b74]">{t("explore.commercialDescription")}</p></div><Select value={commercialUsage} onValueChange={setCommercialUsage}><SelectTrigger aria-label={t("explore.commercial")} className="border-0 bg-white shadow-none"><span>{commercialUsage === "Any usage" ? t("explore.anyUsage") : commercialUsage}</span></SelectTrigger><SelectContent><SelectItem value="Any usage">{t("explore.anyUsage")}</SelectItem><SelectItem value="Office">Office</SelectItem><SelectItem value="Retail">Retail</SelectItem><SelectItem value="F&B">F&amp;B</SelectItem><SelectItem value="Warehouse">Warehouse</SelectItem><SelectItem value="Factory">Factory</SelectItem></SelectContent></Select><div className="grid grid-cols-2 gap-3"><Select value={minFloorLoading} onValueChange={setMinFloorLoading}><SelectTrigger aria-label={t("explore.anyLoading")} className="border-0 bg-white shadow-none"><span>{minFloorLoading === "Any loading" ? t("explore.anyLoading") : `${minFloorLoading}+ kN/m²`}</span></SelectTrigger><SelectContent><SelectItem value="Any loading">{t("explore.anyLoading")}</SelectItem>{[5, 10, 20, 30].map(value => <SelectItem key={value} value={String(value)}>{value}+ kN/m²</SelectItem>)}</SelectContent></Select><Select value={minCeilingHeight} onValueChange={setMinCeilingHeight}><SelectTrigger aria-label={t("explore.anyHeight")} className="border-0 bg-white shadow-none"><span>{minCeilingHeight === "Any height" ? t("explore.anyHeight") : `${minCeilingHeight}+ m`}</span></SelectTrigger><SelectContent><SelectItem value="Any height">{t("explore.anyHeight")}</SelectItem>{[3, 6, 10, 12].map(value => <SelectItem key={value} value={String(value)}>{value}+ m</SelectItem>)}</SelectContent></Select></div></div>}</div></section>
      <section className="container py-10"><h2 className="sr-only">{t("explore.title")}</h2><div className="mb-7 flex items-center justify-between"><p className="text-sm text-[#4e665f]"><strong className="text-[#17382f]">{properties.length}</strong> {t("explore.matched", { properties: market.terminology.propertyPlural })}</p><div className="flex gap-2"><Select value={maxPrice} onValueChange={setMaxPrice}><SelectTrigger aria-label={t("explore.anyPrice")} className="w-[190px] rounded-full bg-transparent"><span>{maxPrice === "Any price" ? t("explore.anyPrice") : t("explore.upTo", { price: `${formatMarketCurrency(Number(maxPrice), market)}${Number(maxPrice) <= 150000 ? ` ${t("card.perMonth")}` : ""}` })}</span></SelectTrigger><SelectContent><SelectItem value="Any price">{t("explore.anyPrice")}</SelectItem>{[25000, 75000, 150000, 5000000, 15000000, 50000000, 75000000].map(value => <SelectItem key={value} value={String(value)}>{t("explore.upTo", { price: `${formatMarketCurrency(value, market)}${value <= 150000 ? ` ${t("card.perMonth")}` : ""}` })}</SelectItem>)}</SelectContent></Select><Button onClick={() => toast.info(t("explore.resultsInfo"))} aria-label={t("explore.resultsInfo")} variant="outline" size="icon" className="rounded-full"><ListFilter className="size-4" /></Button></div></div>
        {isLoading ? <div className="grid gap-6 lg:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-[500px] animate-pulse rounded-[24px] bg-[#e4e8e4]" />)}</div> : properties.length ? <>{properties.some(property => property.isPlanningDemo) && <div className="mb-6 rounded-2xl border border-[#c99d60]/35 bg-[#fbf4e8] px-4 py-3 text-sm leading-6 text-[#725124]" role="note"><strong>{t("demo.planningLabel")}.</strong> {t("demo.planningDisclosure")}</div>}<div className="grid gap-6 lg:grid-cols-3">{properties.map(property => <PropertyCard key={property.id} property={property} />)}</div></> : <div className="rounded-3xl border border-dashed border-[#17382f]/20 py-24 text-center"><Filter className="mx-auto size-8 text-[#a77c43]" /><h2 className="mt-4 font-display text-2xl">{t("explore.noExact")}</h2><p className="mx-auto mt-2 max-w-xl text-sm text-[#647b74]">{market.id === "singapore" ? t("explore.emptySingapore") : t("explore.emptyMarket", { country: market.countryName })}</p><Link href={market.id === "singapore" ? "/assistants" : "/map"}><Button className="mt-6 rounded-full bg-[#17382f]">{market.id === "singapore" ? t("explore.askAi") : t("explore.openMap")}</Button></Link></div>}
      </section>
    </main></div>;
}
