import { useAuth } from "@/_core/hooks/useAuth";
import { BrandHeader } from "@/components/BrandHeader";
import { BuildingViewer } from "@/components/BuildingViewer";
import { VirtualTour } from "@/components/VirtualTour";
import { PropertyIntelligence } from "@/components/PropertyIntelligence";
import { FloorPlanPreview } from "@/components/FloorPlanPreview";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { formatMarketCurrency, getMarketConfig } from "@shared/marketConfig";
import { ArrowLeft, Bath, BedDouble, Bookmark, Building2, CalendarDays, CarFront, ChevronLeft, ChevronRight, Expand, Gauge, MapPin, Maximize2, Move3D, Ruler, Share2, Sparkles, TrainFront, Truck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function PropertyDetail({ params }: { params: { id: string } }) {
  const { data, isLoading } = trpc.property.detail.useQuery({ id: params.id });
  const { isAuthenticated } = useAuth();
  const [activeGallery, setActiveGallery] = useState(0);
  const [galleryOpen, setGalleryOpen] = useState(false);
  useEffect(() => {
    if (!galleryOpen) return;
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setGalleryOpen(false); };
    window.addEventListener("keydown", closeOnEscape);
    return () => window.removeEventListener("keydown", closeOnEscape);
  }, [galleryOpen]);
  const save = trpc.saved.toggle.useMutation({ onSuccess: result => toast.success(result.saved ? "Saved to your collection" : "Removed from saved"), onError: error => toast.error(error.message) });
  if (isLoading) return <div className="min-h-screen bg-[#f5f4ef]"><BrandHeader /><main className="container py-16" aria-busy="true" aria-label="Loading property details"><div className="h-[600px] animate-pulse rounded-3xl bg-[#e4e8e4]" /></main></div>;
  if (!data) return <div className="min-h-screen bg-[#f5f4ef] text-[#17382f]"><BrandHeader /><main className="container py-24 text-center"><Building2 className="mx-auto size-9 text-[#a77c43]" /><h1 className="mt-5 font-display text-4xl">Property not found.</h1><p className="mt-3 text-sm text-[#4e665f]">This asset may no longer be available in the demonstration catalog.</p><Link href="/explore"><Button className="mt-7 rounded-full bg-[#17382f]">Return to properties</Button></Link></main></div>;
  const { property } = data;
  const market = getMarketConfig(property.marketId);
  const money = formatMarketCurrency(property.price, market);
  const isRental = property.mode === "Rent" || property.mode === "Rent-Out";
  const displayedPrice = isRental && property.monthlyRent ? `${formatMarketCurrency(property.monthlyRent, market)} / mo` : money;
  const pricePerArea = isRental && property.monthlyRent ? property.monthlyRent / property.size : property.price / property.size;
  const pricePerAreaLabel = `${formatMarketCurrency(pricePerArea, market, { maximumFractionDigits: isRental ? 2 : 0 })} / ${market.terminology.areaUnit}${isRental ? " / mo" : ""}`;
  const specifications = property.isCommercial
    ? [[Ruler, `${property.size.toLocaleString(market.locale)} ${market.terminology.areaUnit}`], [Gauge, `${property.floorLoading ?? "—"} kN/m² loading`], [Maximize2, `${property.ceilingHeight ?? "—"} m ceiling`], [CarFront, `${property.parkingLots ?? 0} parking lots`]]
    : [[BedDouble, `${property.beds} bedrooms`], [Bath, `${property.baths} bathrooms`], [Ruler, `${property.size.toLocaleString(market.locale)} ${market.terminology.areaUnit}`], [TrainFront, `${property.mrtMinutes} min to ${market.terminology.transit}`]];
  return <div className="min-h-screen bg-[#f7f6f1] text-[#17382f]"><BrandHeader /><main>
    <div className="container py-6"><div className="mb-5 flex items-center justify-between"><Link href="/explore" className="flex items-center gap-2 text-xs font-semibold text-[#647b74] hover:text-[#17382f]"><ArrowLeft className="size-4" />Back to properties</Link><div className="flex gap-2"><Button onClick={() => navigator.clipboard?.writeText(window.location.href).then(() => toast.success("Property link copied"))} variant="outline" size="sm" className="rounded-full bg-white"><Share2 className="mr-2 size-3.5" />Share</Button><Button onClick={() => isAuthenticated ? save.mutate({ propertyId: property.id }) : startLogin()} variant="outline" size="sm" className="rounded-full bg-white"><Bookmark className="mr-2 size-3.5" />Save</Button></div></div>
      <section className="grid gap-3 lg:grid-cols-[1.5fr_.75fr] lg:grid-rows-2"><button aria-label={`Open ${property.title} image gallery`} onClick={() => setGalleryOpen(true)} className="group relative h-[clamp(240px,54svh,360px)] min-h-[240px] overflow-hidden rounded-[28px] sm:h-auto sm:min-h-[440px] lg:row-span-2"><img src={property.gallery[activeGallery]} alt={property.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.02]" /><span className="absolute bottom-4 right-4 flex min-h-11 items-center gap-2 rounded-full bg-white/88 px-3 py-2 text-xs font-semibold backdrop-blur"><Expand className="size-4" />View gallery</span></button>{property.gallery.slice(1,3).map((image, index) => <button aria-label={`View ${property.title} image ${index + 2}`} key={`${image}-${index + 1}`} onClick={() => setActiveGallery(index + 1)} className="hidden min-h-[210px] overflow-hidden rounded-[22px] lg:block"><img src={image} alt={`${property.title} view ${index + 2}`} className="h-full w-full object-cover transition duration-500 hover:scale-105" /></button>)}</section>
      <section className="grid gap-10 py-12 lg:grid-cols-[1fr_360px]"><div><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="eyebrow">{property.type} · {property.tenure}</p><h1 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">{property.title}</h1><p className="mt-3 flex items-center gap-2 text-sm text-[#647b74]"><MapPin className="size-4 text-[#a77c43]" />{property.address} · {property.district}</p></div><div className="text-left lg:text-right"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#71857f]">{isRental ? "Guide rent" : "Guide price"}</p><p className="mt-2 text-3xl font-semibold">{displayedPrice}</p><p className="mt-1 text-xs text-[#71857f]">{pricePerAreaLabel}</p></div></div>
        <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{specifications.map(([Icon, label]) => <div key={label as string} className="rounded-2xl border border-[#17382f]/10 bg-white p-4"><Icon className="size-5 text-[#a77c43]" /><p className="mt-3 text-xs font-semibold">{label as string}</p></div>)}</div>
        {property.isCommercial && <div className="mt-4 grid gap-3 rounded-2xl border border-[#a77c43]/20 bg-[#f4efe4] p-5 sm:grid-cols-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#76552f]">Approved / intended use</p><p className="mt-2 text-sm font-semibold">{property.commercialUsage}</p></div><div><p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#76552f]"><Truck className="size-3.5" />Loading access</p><p className="mt-2 text-sm font-semibold">{property.loadingAccess}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#76552f]">Available from</p><p className="mt-2 text-sm font-semibold">{property.availableFrom ? new Date(`${property.availableFrom}T00:00:00`).toLocaleDateString(market.locale, { day: "numeric", month: "short", year: "numeric" }) : "By arrangement"}</p></div></div>}
        <p className="mt-8 max-w-3xl text-base leading-8 text-[#566f68]">{property.description}</p><div className="mt-6 flex flex-wrap gap-2">{property.tags.map(tag => <span key={tag} className="rounded-full bg-[#e8eee9] px-3 py-1.5 text-xs font-semibold text-[#49635d]">{tag}</span>)}</div>{property.floorPlan && <section className="mt-10 max-w-3xl"><div className="mb-4"><p className="eyebrow">Layout reference</p><h2 className="mt-2 font-display text-3xl">Floor plan</h2></div><FloorPlanPreview floorPlan={property.floorPlan} title={property.title} /></section>}
      </div><aside className="h-fit rounded-[26px] border border-[#17382f]/10 bg-white p-6 shadow-[0_18px_60px_rgba(23,56,47,.08)] lg:sticky lg:top-6"><p className="eyebrow">Private appointment</p><h2 className="mt-3 font-display text-2xl">Experience this {property.isCommercial ? "asset" : "residence"}.</h2><p className="mt-3 text-sm leading-6 text-[#647b74]">Request a viewing or start with the virtual {property.isCommercial ? "property" : "unit"} tour below.</p><Button onClick={() => isAuthenticated ? toast.success("Viewing request started") : startLogin()} className="mt-6 w-full rounded-full bg-[#17382f]">Request a viewing <CalendarDays className="ml-2 size-4" /></Button><Link href="/assistants"><Button variant="outline" className="mt-3 w-full rounded-full"><Sparkles className="mr-2 size-4 text-[#a77c43]" />Ask AI about this property</Button></Link><p className="mt-5 border-t border-[#17382f]/10 pt-4 text-[10px] leading-4 text-[#8a9a95]">Owner details are privacy-protected. Only anonymized ownership context is shown in the intelligence section.</p></aside></section>
    </div>
    <section className="border-y border-[#17382f]/10 bg-[#e9eee9] py-12 sm:py-20"><div className="container"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Immersive model</p><h2 className="mt-3 font-display text-4xl">Understand the building form.</h2></div><p className="max-w-md text-sm leading-6 text-[#647b74]">An interactive conceptual model helps orient stacks, massing, and shared facilities. It is not a survey or as-built plan.</p></div><BuildingViewer propertyId={property.id} propertyType={property.type} transactionUnit={property.transactions.find(transaction => transaction.property === property.title)?.unit} listingFloor={property.listingFloor} listingUnit={property.listingUnit} /></div></section>
    <section className="container py-12 sm:py-20"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow">Virtual viewing</p><h2 className="mt-3 font-display text-4xl">See it in a different light.</h2></div><span className="hidden items-center gap-2 text-xs font-semibold text-[#647b74] sm:flex"><Move3D className="size-4 text-[#a77c43]" />Photo-backed timings where available</span></div><VirtualTour title={property.title} gallery={property.gallery} /></section>
    <PropertyIntelligence property={property} disclaimer={data.disclaimer} />
    <section className="border-t border-[#17382f]/10 py-14"><div className="container flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><p className="eyebrow">Continue the intelligence journey</p><h2 className="mt-3 font-display text-3xl">Review history, ownership context, and transactions.</h2></div><a href="#intelligence"><Button className="rounded-full bg-[#17382f]">Open property intelligence <ChevronRight className="ml-2 size-4" /></Button></a></div></section>
    {galleryOpen && <div role="dialog" aria-modal="true" aria-label={`${property.title} image gallery`} className="fixed inset-0 z-[120] flex flex-col bg-[#081713]/95 p-4 text-white backdrop-blur-lg sm:p-8"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d5ae72]">Property gallery</p><p className="mt-1 font-display text-2xl">{property.title}</p></div><Button aria-label="Close image gallery" onClick={() => setGalleryOpen(false)} size="icon" variant="outline" className="rounded-full border-white/20 bg-white/5 text-white"><X className="size-4" /></Button></div><div className="relative mt-5 min-h-0 flex-1 overflow-hidden rounded-[24px]"><img src={property.gallery[activeGallery]} alt={`${property.title} full-screen view ${activeGallery + 1}`} className="h-full w-full object-contain" /><Button aria-label="Previous gallery image" onClick={() => setActiveGallery(index => (index - 1 + property.gallery.length) % property.gallery.length)} size="icon" className="absolute left-3 top-1/2 -translate-y-1/2 rounded-full bg-white text-[#17382f]"><ChevronLeft className="size-4" /></Button><Button aria-label="Next gallery image" onClick={() => setActiveGallery(index => (index + 1) % property.gallery.length)} size="icon" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full bg-white text-[#17382f]"><ChevronRight className="size-4" /></Button></div><div className="mt-4 flex items-center justify-center gap-2">{property.gallery.map((image, index) => <button key={`${image}-${index}`} aria-label={`Show gallery image ${index + 1}`} aria-current={index === activeGallery} onClick={() => setActiveGallery(index)} className={`h-2 rounded-full transition-all ${index === activeGallery ? "w-8 bg-[#d5ae72]" : "w-2 bg-white/35"}`} />)}</div></div>}
  </main></div>;
}
