export const localeIds = ["en", "id", "ms", "th", "vi", "zh-Hans"] as const;

export type LocaleId = (typeof localeIds)[number];

export type LocaleConfig = {
  id: LocaleId;
  languageTag: string;
  label: string;
  nativeLabel: string;
  region: "Southeast Asia";
};

export const localeConfigs: Record<LocaleId, LocaleConfig> = {
  en: { id: "en", languageTag: "en", label: "English", nativeLabel: "English", region: "Southeast Asia" },
  id: { id: "id", languageTag: "id", label: "Indonesian", nativeLabel: "Bahasa Indonesia", region: "Southeast Asia" },
  ms: { id: "ms", languageTag: "ms", label: "Malay", nativeLabel: "Bahasa Melayu", region: "Southeast Asia" },
  th: { id: "th", languageTag: "th", label: "Thai", nativeLabel: "ไทย", region: "Southeast Asia" },
  vi: { id: "vi", languageTag: "vi", label: "Vietnamese", nativeLabel: "Tiếng Việt", region: "Southeast Asia" },
  "zh-Hans": { id: "zh-Hans", languageTag: "zh-Hans", label: "Simplified Chinese", nativeLabel: "简体中文", region: "Southeast Asia" },
};

export const localeOptions = localeIds.map(id => localeConfigs[id]);
export const defaultLocaleId: LocaleId = "en";

const englishMessages = {
  "nav.buy": "Buy", "nav.rent": "Rent", "nav.sell": "Sell", "nav.rentOut": "Rent out", "nav.map": "Map intelligence", "nav.ai": "AI concierge", "nav.agent": "Agent portal", "nav.plans": "Plans", "nav.search": "Search properties", "nav.chooseMarket": "Choose active property market", "nav.chooseLanguage": "Choose display language", "nav.signIn": "Sign in", "nav.menu": "Toggle menu",
  "home.eyebrow": "{country} property, understood", "home.titleLead": "Find the address", "home.titleEmphasis": "fits your life.", "home.intro": "Explore homes through immersive maps, verified-context tools, transaction intelligence, and a concierge that understands what matters to you.", "home.search": "Home, {region}, {transit} or street", "home.explore": "Explore", "home.privacy": "Privacy-first insights", "home.transitDiscovery": "{transit}-aware discovery", "home.context": "Context with disclaimers", "home.activeMarket": "Active market", "home.profileLoaded": "geography and map profile loaded", "home.featureMap": "3D {region} map", "home.featureMapDesc": "Explore context, not just pins", "home.immersive": "Immersive viewing", "home.immersiveDesc": "Tour day and night", "home.transaction": "Transaction lens", "home.transactionDesc": "Read the price journey", "home.matching": "AI matching", "home.matchingDesc": "Explain what fits and why", "home.curated": "Curated residences", "home.homesTitle": "Homes with a clearer story.", "home.homesDescription": "Move beyond surface details with immersive views, ownership context, and a transparent record of curated highlights and reported concerns.", "home.viewAll": "View all properties", "home.catalogReady": "{country} is ready for a local catalog.", "home.catalogDescription": "Its map, currency, regional taxonomy, and property terminology are configured. Connect local listing data to publish market-specific inventory.", "home.spatial": "Spatial intelligence", "home.seeAddress": "See the whole address.", "home.seeAddressDesc": "Building form, local context, transit radius, and neighborhood boundaries in one view.", "home.spatialTitle": "{country}, layered around your priorities.", "home.spatialDescription": "Tilt into a 3D perspective, reveal nearby transport, compare {region} boundaries, and move from neighborhood scale to unit-level detail without losing context.", "home.buildingFootprints": "3D building footprints", "home.transitRadii": "{transit} travel-time radii", "home.regionOverlays": "{region} boundary overlays", "home.clusteredSignals": "Clustered property signals", "home.openMap": "Open map intelligence", "home.intelligence": "UrbanKey Intelligence", "home.conciergeTitle": "Tell us how you want to live. We’ll translate it into places.", "home.conciergeDescription": "Our buyer and tenant concierge reasons across commute, budget, tenure, space, and lifestyle. A separate professional mode supports agents and co-brokers.", "home.meetConcierge": "Meet your AI concierge", "home.platform": "{country} configurable property intelligence platform.", "home.privacyDesign": "Privacy by design", "home.demoData": "Curated demo data", "home.verify": "Independent verification required",
  "explore.discover": "Discover {country}", "explore.title": "Properties, seen in context.", "explore.onMap": "Explore on map", "explore.search": "Search address, {transit} or {region}", "explore.listingMode": "Listing mode", "explore.allRegions": "All {region}", "explore.allTypes": "All types", "explore.propertyType": "Property type", "explore.anyOwnership": "Any ownership", "explore.minArea": "Minimum floor area", "explore.anySize": "Any size", "explore.anyTravel": "Any {transit} travel time", "explore.within": "Within {minutes} min", "explore.commercial": "Commercial operations", "explore.commercialDescription": "Refine by intended use and physical capability.", "explore.anyUsage": "Any usage", "explore.anyLoading": "Any loading", "explore.anyHeight": "Any height", "explore.matched": "thoughtfully matched {properties}", "explore.anyPrice": "Any price", "explore.upTo": "Up to {price}", "explore.resultsInfo": "Results are currently ordered by contextual match.", "explore.noExact": "No exact match yet", "explore.emptySingapore": "Try widening a filter or ask the AI concierge to reason across your priorities.", "explore.emptyMarket": "{country} is configured for local geography, currency, terminology, and mapping. Connect a local listing feed to see market inventory here.", "explore.askAi": "Ask AI concierge", "explore.openMap": "Open configured map",
  "card.saved": "Saved to your collection", "card.removed": "Removed from saved properties", "card.forSale": "For sale", "card.ownerSale": "Owner sale", "card.forRent": "For rent", "card.ownerLease": "Owner lease", "card.save": "Save property", "card.lots": "lots", "card.minute": "min", "card.guideRent": "Guide rent", "card.guidePrice": "Guide price", "card.view": "View {title}", "card.perMonth": "/ mo",
  "demo.planningLabel": "Illustrative planning demo", "demo.planningDisclosure": "Illustrative planning-demo inventory only. These entries are not live, available, or verified listings and must not be used to assess price, availability, ownership, or local market conditions.",
  "map.eyebrow": "Map intelligence", "map.title": "Explore by context.", "map.description": "Tilt, zoom, and compare homes, commercial assets, and local context across {country}.", "map.loading": "Loading mapped assets…", "map.mapped": "{count} listed assets currently mapped", "map.empty": "{country} map profile loaded — connect local inventory to add assets", "map.homes": "Homes", "map.commercial": "Commercial / industrial", "map.threeD": "3D building perspective", "map.boundaries": "{region} boundaries", "map.transitRadius": "{transit} travel-time radius", "map.recenter": "Recenter", "map.commute": "Commute", "map.commuteInfo": "Choose a workplace, school, port, or logistics node to configure local commute-time routing.", "map.footer": "Google Maps · Illustrative {region} and {transit} overlays · Zoom out to cluster", "map.closePreview": "Close property preview", "map.beds": "beds", "map.clear": "m clear", "map.viewProperty": "View property", "map.showPanels": "Show panels", "map.hidePanels": "Hide panels", "map.homePin": "HOME", "map.commercialPin": "C/I", "map.assets": "assets", "map.viewAsset": "View {title}", "map.zoomAssets": "Zoom into {count} {properties}",
} as const;

export type TranslationKey = keyof typeof englishMessages;
export type TranslationValues = Record<string, string | number>;
export type TranslationDictionary = Record<TranslationKey, string>;

const withEnglishFallback = (overrides: Partial<TranslationDictionary>): TranslationDictionary => ({ ...englishMessages, ...overrides });

export const translationDictionaries: Record<LocaleId, TranslationDictionary> = {
  en: englishMessages,
  id: withEnglishFallback({
    "nav.buy": "Beli", "nav.rent": "Sewa", "nav.sell": "Jual", "nav.rentOut": "Sewakan", "nav.map": "Kecerdasan peta", "nav.ai": "Asisten AI", "nav.agent": "Portal agen", "nav.plans": "Paket", "nav.search": "Cari properti", "nav.chooseMarket": "Pilih pasar properti aktif", "nav.chooseLanguage": "Pilih bahasa tampilan", "nav.signIn": "Masuk", "nav.menu": "Buka menu",
    "home.eyebrow": "Properti {country}, dipahami", "home.titleLead": "Temukan alamat yang", "home.titleEmphasis": "sesuai hidup Anda.", "home.intro": "Jelajahi hunian melalui peta imersif, alat konteks terverifikasi, kecerdasan transaksi, dan asisten yang memahami prioritas Anda.", "home.search": "Rumah, {region}, {transit}, atau jalan", "home.explore": "Jelajahi", "home.privacy": "Wawasan yang mengutamakan privasi", "home.transitDiscovery": "Pencarian berbasis {transit}", "home.context": "Konteks dengan penafian", "home.activeMarket": "Pasar aktif", "home.profileLoaded": "profil geografi dan peta dimuat", "home.featureMap": "Peta {region} 3D", "home.featureMapDesc": "Jelajahi konteks, bukan hanya pin", "home.immersive": "Tampilan imersif", "home.immersiveDesc": "Tur siang dan malam", "home.transaction": "Analisis transaksi", "home.transactionDesc": "Baca perjalanan harga", "home.matching": "Pencocokan AI", "home.matchingDesc": "Jelaskan yang cocok dan alasannya", "home.curated": "Hunian terkurasi", "home.homesTitle": "Hunian dengan cerita yang lebih jelas.", "home.homesDescription": "Lihat melampaui detail permukaan dengan tampilan imersif, konteks kepemilikan, dan catatan transparan tentang sorotan serta perhatian yang dilaporkan.", "home.viewAll": "Lihat semua properti", "home.catalogReady": "{country} siap untuk katalog lokal.", "home.catalogDescription": "Peta, mata uang, taksonomi wilayah, dan istilah propertinya telah dikonfigurasi. Hubungkan data listing lokal untuk menerbitkan inventaris khusus pasar.", "home.spatial": "Kecerdasan spasial", "home.seeAddress": "Lihat alamat secara utuh.", "home.seeAddressDesc": "Bentuk bangunan, konteks lokal, radius transit, dan batas lingkungan dalam satu tampilan.", "home.spatialTitle": "{country}, disusun untuk prioritas Anda.", "home.spatialDescription": "Gunakan perspektif 3D, lihat transportasi terdekat, bandingkan batas {region}, dan berpindah dari skala lingkungan ke detail unit tanpa kehilangan konteks.", "home.buildingFootprints": "Jejak bangunan 3D", "home.transitRadii": "Radius waktu perjalanan {transit}", "home.regionOverlays": "Overlay batas {region}", "home.clusteredSignals": "Sinyal properti berkelompok", "home.openMap": "Buka kecerdasan peta", "home.conciergeTitle": "Ceritakan cara hidup Anda. Kami menerjemahkannya menjadi tempat.", "home.conciergeDescription": "Asisten pembeli dan penyewa kami mempertimbangkan perjalanan, anggaran, tenur, ruang, dan gaya hidup.", "home.meetConcierge": "Temui asisten AI Anda", "home.platform": "Platform intelijen properti {country} yang dapat dikonfigurasi.", "home.privacyDesign": "Privasi sejak desain", "home.demoData": "Data demo terkurasi", "home.verify": "Perlu verifikasi independen",
    "explore.discover": "Jelajahi {country}", "explore.title": "Properti, dilihat dalam konteks.", "explore.onMap": "Jelajahi di peta", "explore.search": "Cari alamat, {transit}, atau {region}", "explore.listingMode": "Mode listing", "explore.allRegions": "Semua {region}", "explore.allTypes": "Semua tipe", "explore.propertyType": "Tipe properti", "explore.anyOwnership": "Kepemilikan apa pun", "explore.minArea": "Luas lantai minimum", "explore.anySize": "Ukuran apa pun", "explore.anyTravel": "Waktu perjalanan {transit} apa pun", "explore.within": "Dalam {minutes} menit", "explore.commercial": "Operasi komersial", "explore.commercialDescription": "Persempit berdasarkan penggunaan dan kemampuan fisik.", "explore.anyUsage": "Penggunaan apa pun", "explore.anyLoading": "Beban apa pun", "explore.anyHeight": "Tinggi apa pun", "explore.matched": "{properties} yang cocok", "explore.anyPrice": "Harga apa pun", "explore.upTo": "Hingga {price}", "explore.resultsInfo": "Hasil saat ini diurutkan berdasarkan kecocokan kontekstual.", "explore.noExact": "Belum ada kecocokan tepat", "explore.emptySingapore": "Coba perluas filter atau minta asisten AI mempertimbangkan prioritas Anda.", "explore.emptyMarket": "{country} telah dikonfigurasi untuk geografi, mata uang, istilah, dan pemetaan lokal. Hubungkan data listing lokal untuk melihat inventaris.", "explore.askAi": "Tanya asisten AI", "explore.openMap": "Buka peta yang dikonfigurasi",
    "card.saved": "Disimpan ke koleksi Anda", "card.removed": "Dihapus dari properti tersimpan", "card.forSale": "Dijual", "card.ownerSale": "Penjualan pemilik", "card.forRent": "Disewakan", "card.ownerLease": "Sewa pemilik", "card.save": "Simpan properti", "card.lots": "lot", "card.minute": "mnt", "card.guideRent": "Sewa panduan", "card.guidePrice": "Harga panduan", "card.view": "Lihat {title}", "card.perMonth": "/ bln",
    "map.eyebrow": "Kecerdasan peta", "map.title": "Jelajahi berdasarkan konteks.", "map.description": "Miringkan, perbesar, dan bandingkan hunian, aset komersial, serta konteks lokal di {country}.", "map.loading": "Memuat aset yang dipetakan…", "map.mapped": "{count} aset listing sedang dipetakan", "map.empty": "Profil peta {country} dimuat — hubungkan inventaris lokal untuk menambahkan aset", "map.homes": "Hunian", "map.commercial": "Komersial / industri", "map.threeD": "Perspektif bangunan 3D", "map.boundaries": "Batas {region}", "map.transitRadius": "Radius waktu perjalanan {transit}", "map.recenter": "Pusatkan", "map.commute": "Perjalanan", "map.commuteInfo": "Pilih tempat kerja, sekolah, pelabuhan, atau simpul logistik untuk mengonfigurasi rute perjalanan lokal.", "map.footer": "Google Maps · Overlay {region} dan {transit} ilustratif · Perkecil untuk mengelompokkan", "map.closePreview": "Tutup pratinjau properti", "map.beds": "kamar", "map.clear": "m bersih", "map.viewProperty": "Lihat properti", "map.showPanels": "Tampilkan panel", "map.hidePanels": "Sembunyikan panel", "map.assets": "aset", "map.viewAsset": "Lihat {title}", "map.zoomAssets": "Perbesar ke {count} {properties}",
  }),
  ms: withEnglishFallback({
    "nav.buy": "Beli", "nav.rent": "Sewa", "nav.sell": "Jual", "nav.rentOut": "Sewakan", "nav.map": "Kecerdasan peta", "nav.ai": "Pembantu AI", "nav.agent": "Portal ejen", "nav.plans": "Pelan", "nav.search": "Cari hartanah", "nav.chooseMarket": "Pilih pasaran hartanah aktif", "nav.chooseLanguage": "Pilih bahasa paparan", "nav.signIn": "Log masuk", "nav.menu": "Togol menu",
    "home.eyebrow": "Hartanah {country}, difahami", "home.titleLead": "Cari alamat yang", "home.titleEmphasis": "sesuai dengan hidup anda.", "home.intro": "Terokai kediaman melalui peta imersif, alat konteks yang disahkan, kecerdasan transaksi, dan pembantu yang memahami keutamaan anda.", "home.search": "Rumah, {region}, {transit} atau jalan", "home.explore": "Teroka", "home.privacy": "Wawasan mengutamakan privasi", "home.transitDiscovery": "Carian berasaskan {transit}", "home.context": "Konteks dengan penafian", "home.activeMarket": "Pasaran aktif", "home.profileLoaded": "profil geografi dan peta dimuatkan", "home.featureMap": "Peta {region} 3D", "home.featureMapDesc": "Teroka konteks, bukan hanya pin", "home.immersive": "Paparan imersif", "home.immersiveDesc": "Lawatan siang dan malam", "home.transaction": "Lensa transaksi", "home.transactionDesc": "Baca perjalanan harga", "home.matching": "Padanan AI", "home.matchingDesc": "Terangkan yang sesuai dan sebabnya", "home.curated": "Kediaman terpilih", "home.homesTitle": "Rumah dengan cerita yang lebih jelas.", "home.homesDescription": "Lihat melangkaui butiran permukaan dengan pandangan imersif, konteks pemilikan, dan rekod telus tentang sorotan serta kebimbangan yang dilaporkan.", "home.viewAll": "Lihat semua hartanah", "home.catalogReady": "{country} sedia untuk katalog tempatan.", "home.catalogDescription": "Peta, mata wang, taksonomi wilayah dan istilah hartanahnya telah dikonfigurasi. Sambungkan data senarai tempatan untuk menerbitkan inventori khusus pasaran.", "home.spatial": "Kecerdasan ruang", "home.seeAddress": "Lihat keseluruhan alamat.", "home.seeAddressDesc": "Bentuk bangunan, konteks tempatan, radius transit dan sempadan kejiranan dalam satu paparan.", "home.spatialTitle": "{country}, disusun mengikut keutamaan anda.", "home.spatialDescription": "Gunakan perspektif 3D, dedahkan pengangkutan berhampiran, bandingkan sempadan {region}, dan bergerak dari skala kejiranan ke butiran unit tanpa kehilangan konteks.", "home.buildingFootprints": "Jejak bangunan 3D", "home.transitRadii": "Radius masa perjalanan {transit}", "home.regionOverlays": "Lapisan sempadan {region}", "home.clusteredSignals": "Isyarat hartanah berkelompok", "home.openMap": "Buka kecerdasan peta", "home.conciergeTitle": "Beritahu cara anda mahu hidup. Kami akan menterjemahkannya kepada tempat.", "home.conciergeDescription": "Pembantu pembeli dan penyewa kami mengambil kira perjalanan, bajet, tempoh milikan, ruang dan gaya hidup.", "home.meetConcierge": "Temui pembantu AI anda", "home.platform": "Platform kecerdasan hartanah {country} yang boleh dikonfigurasi.", "home.privacyDesign": "Privasi melalui reka bentuk", "home.demoData": "Data demo terpilih", "home.verify": "Pengesahan bebas diperlukan",
    "explore.discover": "Terokai {country}", "explore.title": "Hartanah, dilihat dalam konteks.", "explore.onMap": "Teroka pada peta", "explore.search": "Cari alamat, {transit} atau {region}", "explore.listingMode": "Mod senarai", "explore.allRegions": "Semua {region}", "explore.allTypes": "Semua jenis", "explore.propertyType": "Jenis hartanah", "explore.anyOwnership": "Sebarang pemilikan", "explore.minArea": "Keluasan lantai minimum", "explore.anySize": "Sebarang saiz", "explore.anyTravel": "Sebarang masa perjalanan {transit}", "explore.within": "Dalam {minutes} min", "explore.commercial": "Operasi komersial", "explore.commercialDescription": "Tapis mengikut kegunaan dan keupayaan fizikal.", "explore.anyUsage": "Sebarang kegunaan", "explore.anyLoading": "Sebarang beban", "explore.anyHeight": "Sebarang ketinggian", "explore.matched": "{properties} yang sepadan", "explore.anyPrice": "Sebarang harga", "explore.upTo": "Sehingga {price}", "explore.resultsInfo": "Hasil kini disusun mengikut padanan kontekstual.", "explore.noExact": "Belum ada padanan tepat", "explore.emptySingapore": "Cuba luaskan penapis atau minta pembantu AI mempertimbangkan keutamaan anda.", "explore.emptyMarket": "{country} dikonfigurasikan untuk geografi, mata wang, istilah dan pemetaan tempatan. Sambungkan data senarai tempatan untuk melihat inventori.", "explore.askAi": "Tanya pembantu AI", "explore.openMap": "Buka peta dikonfigurasi",
    "card.saved": "Disimpan ke koleksi anda", "card.removed": "Dialih keluar daripada hartanah tersimpan", "card.forSale": "Untuk dijual", "card.ownerSale": "Jualan pemilik", "card.forRent": "Untuk disewa", "card.ownerLease": "Sewaan pemilik", "card.save": "Simpan hartanah", "card.lots": "lot", "card.minute": "min", "card.guideRent": "Sewa panduan", "card.guidePrice": "Harga panduan", "card.view": "Lihat {title}", "card.perMonth": "/ bln",
    "map.eyebrow": "Kecerdasan peta", "map.title": "Teroka mengikut konteks.", "map.description": "Condongkan, zum dan bandingkan rumah, aset komersial serta konteks tempatan di {country}.", "map.loading": "Memuatkan aset dipetakan…", "map.mapped": "{count} aset senarai kini dipetakan", "map.empty": "Profil peta {country} dimuatkan — sambungkan inventori tempatan untuk menambah aset", "map.homes": "Rumah", "map.commercial": "Komersial / industri", "map.threeD": "Perspektif bangunan 3D", "map.boundaries": "Sempadan {region}", "map.transitRadius": "Radius masa perjalanan {transit}", "map.recenter": "Pusatkan", "map.commute": "Perjalanan", "map.commuteInfo": "Pilih tempat kerja, sekolah, pelabuhan atau hab logistik untuk mengkonfigurasi laluan perjalanan tempatan.", "map.footer": "Google Maps · Lapisan {region} dan {transit} ilustratif · Zum keluar untuk mengelompok", "map.closePreview": "Tutup pratonton hartanah", "map.beds": "bilik", "map.clear": "m bersih", "map.viewProperty": "Lihat hartanah", "map.showPanels": "Tunjuk panel", "map.hidePanels": "Sembunyi panel", "map.assets": "aset", "map.viewAsset": "Lihat {title}", "map.zoomAssets": "Zum kepada {count} {properties}",
  }),
  th: withEnglishFallback({
    "nav.buy": "ซื้อ", "nav.rent": "เช่า", "nav.sell": "ขาย", "nav.rentOut": "ปล่อยเช่า", "nav.map": "ข้อมูลแผนที่", "nav.ai": "ผู้ช่วย AI", "nav.agent": "พอร์ทัลเอเจนต์", "nav.plans": "แพ็กเกจ", "nav.search": "ค้นหาอสังหาริมทรัพย์", "nav.chooseMarket": "เลือกตลาดอสังหาริมทรัพย์", "nav.chooseLanguage": "เลือกภาษาที่แสดง", "nav.signIn": "เข้าสู่ระบบ", "nav.menu": "เปิดเมนู",
    "home.eyebrow": "เข้าใจอสังหาริมทรัพย์ใน{country}", "home.titleLead": "ค้นหาที่อยู่ที่", "home.titleEmphasis": "เหมาะกับชีวิตคุณ", "home.intro": "สำรวจบ้านผ่านแผนที่เสมือนจริง เครื่องมือข้อมูลที่ตรวจสอบได้ ข่าวสารการซื้อขาย และผู้ช่วยที่เข้าใจสิ่งสำคัญสำหรับคุณ", "home.search": "บ้าน {region} {transit} หรือถนน", "home.explore": "สำรวจ", "home.privacy": "ข้อมูลเชิงลึกที่ให้ความสำคัญกับความเป็นส่วนตัว", "home.transitDiscovery": "ค้นหาตาม {transit}", "home.context": "ข้อมูลพร้อมข้อจำกัดความรับผิด", "home.activeMarket": "ตลาดที่เลือก", "home.profileLoaded": "โหลดโปรไฟล์ภูมิศาสตร์และแผนที่แล้ว", "home.featureMap": "แผนที่ {region} 3 มิติ", "home.featureMapDesc": "สำรวจบริบท ไม่ใช่แค่หมุด", "home.immersive": "มุมมองเสมือนจริง", "home.immersiveDesc": "ทัวร์กลางวันและกลางคืน", "home.transaction": "มุมมองการซื้อขาย", "home.transactionDesc": "ดูเส้นทางราคา", "home.matching": "การจับคู่ด้วย AI", "home.matchingDesc": "อธิบายสิ่งที่เหมาะและเหตุผล", "home.curated": "ที่อยู่อาศัยคัดสรร", "home.homesTitle": "บ้านที่มีเรื่องราวชัดเจนขึ้น", "home.homesDescription": "มองลึกกว่ารายละเอียดผิวเผินด้วยมุมมองเสมือนจริง บริบทการถือครอง และบันทึกประเด็นสำคัญอย่างโปร่งใส", "home.viewAll": "ดูอสังหาริมทรัพย์ทั้งหมด", "home.catalogReady": "{country} พร้อมสำหรับแคตตาล็อกท้องถิ่น", "home.catalogDescription": "กำหนดค่าแผนที่ สกุลเงิน ระบบภูมิภาค และคำศัพท์อสังหาริมทรัพย์แล้ว เชื่อมต่อข้อมูลรายการท้องถิ่นเพื่อเผยแพร่สินค้าคงคลัง", "home.spatial": "ข้อมูลเชิงพื้นที่", "home.seeAddress": "เห็นที่อยู่ครบทุกมุม", "home.seeAddressDesc": "รูปแบบอาคาร บริบทท้องถิ่น รัศมีขนส่ง และขอบเขตย่านในมุมมองเดียว", "home.spatialTitle": "{country} ที่จัดวางตามสิ่งที่คุณให้ความสำคัญ", "home.spatialDescription": "ใช้มุมมอง 3 มิติ ดูการเดินทางใกล้เคียง เปรียบเทียบขอบเขต {region} และเปลี่ยนจากระดับย่านสู่รายละเอียดยูนิตโดยไม่เสียบริบท", "home.buildingFootprints": "โครงร่างอาคาร 3 มิติ", "home.transitRadii": "รัศมีเวลาเดินทาง {transit}", "home.regionOverlays": "ชั้นข้อมูลขอบเขต {region}", "home.clusteredSignals": "สัญญาณอสังหาริมทรัพย์แบบกลุ่ม", "home.openMap": "เปิดข้อมูลแผนที่", "home.conciergeTitle": "บอกเราว่าคุณอยากใช้ชีวิตอย่างไร เราจะแปลงเป็นสถานที่ให้คุณ", "home.conciergeDescription": "ผู้ช่วยผู้ซื้อและผู้เช่าของเราพิจารณาการเดินทาง งบประมาณ ระยะถือครอง พื้นที่ และไลฟ์สไตล์", "home.meetConcierge": "พบผู้ช่วย AI ของคุณ", "home.platform": "แพลตฟอร์มข้อมูลอสังหาริมทรัพย์ {country} ที่กำหนดค่าได้", "home.privacyDesign": "คำนึงถึงความเป็นส่วนตัว", "home.demoData": "ข้อมูลสาธิตคัดสรร", "home.verify": "ต้องตรวจสอบอย่างอิสระ",
    "explore.discover": "สำรวจ {country}", "explore.title": "อสังหาริมทรัพย์ในบริบท", "explore.onMap": "สำรวจบนแผนที่", "explore.search": "ค้นหาที่อยู่ {transit} หรือ {region}", "explore.listingMode": "รูปแบบรายการ", "explore.allRegions": "ทุก{region}", "explore.allTypes": "ทุกประเภท", "explore.propertyType": "ประเภทอสังหาริมทรัพย์", "explore.anyOwnership": "การถือครองทั้งหมด", "explore.minArea": "พื้นที่ขั้นต่ำ", "explore.anySize": "ทุกขนาด", "explore.anyTravel": "เวลาเดินทาง {transit} ทั้งหมด", "explore.within": "ภายใน {minutes} นาที", "explore.commercial": "การดำเนินงานเชิงพาณิชย์", "explore.commercialDescription": "กรองตามการใช้งานและความสามารถทางกายภาพ", "explore.anyUsage": "การใช้งานทั้งหมด", "explore.anyLoading": "น้ำหนักบรรทุกทั้งหมด", "explore.anyHeight": "ทุกความสูง", "explore.matched": "{properties} ที่ตรงกัน", "explore.anyPrice": "ทุกช่วงราคา", "explore.upTo": "สูงสุด {price}", "explore.resultsInfo": "ผลลัพธ์เรียงตามความเหมาะสมเชิงบริบท", "explore.noExact": "ยังไม่พบผลที่ตรง", "explore.emptySingapore": "ลองขยายตัวกรองหรือให้ผู้ช่วย AI พิจารณาตามความสำคัญของคุณ", "explore.emptyMarket": "{country} ได้รับการกำหนดค่าสำหรับภูมิศาสตร์ สกุลเงิน คำศัพท์ และแผนที่ท้องถิ่น เชื่อมต่อข้อมูลรายการท้องถิ่นเพื่อดูสินค้าคงคลัง", "explore.askAi": "ถามผู้ช่วย AI", "explore.openMap": "เปิดแผนที่ที่กำหนดค่าแล้ว",
    "card.saved": "บันทึกลงคอลเลกชันแล้ว", "card.removed": "นำออกจากรายการที่บันทึกแล้ว", "card.forSale": "ขาย", "card.ownerSale": "ขายโดยเจ้าของ", "card.forRent": "ให้เช่า", "card.ownerLease": "ปล่อยเช่าโดยเจ้าของ", "card.save": "บันทึกอสังหาริมทรัพย์", "card.lots": "ที่จอด", "card.minute": "นาที", "card.guideRent": "ค่าเช่าแนะนำ", "card.guidePrice": "ราคาแนะนำ", "card.view": "ดู {title}", "card.perMonth": "/ เดือน",
    "map.eyebrow": "ข้อมูลแผนที่", "map.title": "สำรวจด้วยบริบท", "map.description": "ปรับมุม ซูม และเปรียบเทียบบ้าน สินทรัพย์เชิงพาณิชย์ และบริบทท้องถิ่นทั่ว{country}", "map.loading": "กำลังโหลดสินทรัพย์บนแผนที่…", "map.mapped": "มีสินทรัพย์ {count} รายการบนแผนที่", "map.empty": "โหลดโปรไฟล์แผนที่ {country} แล้ว — เชื่อมต่อสินค้าคงคลังท้องถิ่นเพื่อเพิ่มสินทรัพย์", "map.homes": "บ้าน", "map.commercial": "พาณิชย์ / อุตสาหกรรม", "map.threeD": "มุมมองอาคาร 3 มิติ", "map.boundaries": "ขอบเขต {region}", "map.transitRadius": "รัศมีเวลาเดินทาง {transit}", "map.recenter": "จัดกึ่งกลาง", "map.commute": "การเดินทาง", "map.commuteInfo": "เลือกที่ทำงาน โรงเรียน ท่าเรือ หรือศูนย์โลจิสติกส์เพื่อกำหนดเส้นทางการเดินทางท้องถิ่น", "map.footer": "Google Maps · ชั้นข้อมูล {region} และ {transit} เพื่อประกอบการอธิบาย · ซูมออกเพื่อจัดกลุ่ม", "map.closePreview": "ปิดตัวอย่างอสังหาริมทรัพย์", "map.beds": "ห้องนอน", "map.clear": "ม. ความสูงโล่ง", "map.viewProperty": "ดูอสังหาริมทรัพย์", "map.showPanels": "แสดงแผง", "map.hidePanels": "ซ่อนแผง", "map.assets": "สินทรัพย์", "map.viewAsset": "ดู {title}", "map.zoomAssets": "ซูมไปยัง {count} {properties}",
  }),
  vi: withEnglishFallback({
    "nav.buy": "Mua", "nav.rent": "Thuê", "nav.sell": "Bán", "nav.rentOut": "Cho thuê", "nav.map": "Bản đồ thông minh", "nav.ai": "Trợ lý AI", "nav.agent": "Cổng đại lý", "nav.plans": "Gói dịch vụ", "nav.search": "Tìm bất động sản", "nav.chooseMarket": "Chọn thị trường bất động sản", "nav.chooseLanguage": "Chọn ngôn ngữ hiển thị", "nav.signIn": "Đăng nhập", "nav.menu": "Mở menu",
    "home.eyebrow": "Hiểu rõ bất động sản {country}", "home.titleLead": "Tìm địa chỉ", "home.titleEmphasis": "phù hợp với cuộc sống của bạn.", "home.intro": "Khám phá nhà ở qua bản đồ trực quan, công cụ ngữ cảnh đã xác minh, thông tin giao dịch và trợ lý hiểu điều quan trọng với bạn.", "home.search": "Nhà, {region}, {transit} hoặc đường", "home.explore": "Khám phá", "home.privacy": "Thông tin ưu tiên quyền riêng tư", "home.transitDiscovery": "Khám phá theo {transit}", "home.context": "Ngữ cảnh kèm lưu ý", "home.activeMarket": "Thị trường đang chọn", "home.profileLoaded": "đã tải hồ sơ địa lý và bản đồ", "home.featureMap": "Bản đồ {region} 3D", "home.featureMapDesc": "Khám phá bối cảnh, không chỉ ghim", "home.immersive": "Trải nghiệm trực quan", "home.immersiveDesc": "Tham quan ngày và đêm", "home.transaction": "Góc nhìn giao dịch", "home.transactionDesc": "Theo dõi hành trình giá", "home.matching": "Gợi ý AI", "home.matchingDesc": "Giải thích điều phù hợp và lý do", "home.curated": "Nhà ở tuyển chọn", "home.homesTitle": "Những ngôi nhà có câu chuyện rõ ràng hơn.", "home.homesDescription": "Vượt qua các chi tiết bề mặt với góc nhìn trực quan, bối cảnh sở hữu và hồ sơ minh bạch về các điểm đáng chú ý.", "home.viewAll": "Xem tất cả bất động sản", "home.catalogReady": "{country} đã sẵn sàng cho danh mục địa phương.", "home.catalogDescription": "Bản đồ, tiền tệ, phân loại khu vực và thuật ngữ bất động sản đã được cấu hình. Kết nối dữ liệu niêm yết địa phương để công bố nguồn cung theo thị trường.", "home.spatial": "Thông tin không gian", "home.seeAddress": "Xem toàn bộ địa chỉ.", "home.seeAddressDesc": "Hình dáng công trình, bối cảnh địa phương, bán kính giao thông và ranh giới khu phố trong một góc nhìn.", "home.spatialTitle": "{country}, theo các ưu tiên của bạn.", "home.spatialDescription": "Nghiêng sang góc nhìn 3D, xem giao thông gần đó, so sánh ranh giới {region} và đi từ quy mô khu phố đến chi tiết căn hộ mà không mất bối cảnh.", "home.buildingFootprints": "Dấu vết công trình 3D", "home.transitRadii": "Bán kính thời gian di chuyển {transit}", "home.regionOverlays": "Lớp ranh giới {region}", "home.clusteredSignals": "Tín hiệu bất động sản theo cụm", "home.openMap": "Mở bản đồ thông minh", "home.conciergeTitle": "Hãy cho chúng tôi biết bạn muốn sống thế nào. Chúng tôi sẽ biến điều đó thành địa điểm.", "home.conciergeDescription": "Trợ lý cho người mua và người thuê xem xét hành trình, ngân sách, thời hạn sở hữu, không gian và lối sống.", "home.meetConcierge": "Gặp trợ lý AI của bạn", "home.platform": "Nền tảng thông tin bất động sản {country} có thể cấu hình.", "home.privacyDesign": "Quyền riêng tư ngay từ thiết kế", "home.demoData": "Dữ liệu minh họa tuyển chọn", "home.verify": "Cần xác minh độc lập",
    "explore.discover": "Khám phá {country}", "explore.title": "Bất động sản trong bối cảnh.", "explore.onMap": "Khám phá trên bản đồ", "explore.search": "Tìm địa chỉ, {transit} hoặc {region}", "explore.listingMode": "Hình thức niêm yết", "explore.allRegions": "Tất cả {region}", "explore.allTypes": "Mọi loại", "explore.propertyType": "Loại bất động sản", "explore.anyOwnership": "Mọi hình thức sở hữu", "explore.minArea": "Diện tích sàn tối thiểu", "explore.anySize": "Mọi diện tích", "explore.anyTravel": "Mọi thời gian di chuyển {transit}", "explore.within": "Trong {minutes} phút", "explore.commercial": "Hoạt động thương mại", "explore.commercialDescription": "Lọc theo mục đích sử dụng và khả năng vật lý.", "explore.anyUsage": "Mọi mục đích", "explore.anyLoading": "Mọi tải trọng", "explore.anyHeight": "Mọi chiều cao", "explore.matched": "{properties} phù hợp", "explore.anyPrice": "Mọi mức giá", "explore.upTo": "Tối đa {price}", "explore.resultsInfo": "Kết quả hiện được sắp xếp theo mức độ phù hợp ngữ cảnh.", "explore.noExact": "Chưa có kết quả khớp chính xác", "explore.emptySingapore": "Hãy thử mở rộng bộ lọc hoặc nhờ trợ lý AI cân nhắc các ưu tiên của bạn.", "explore.emptyMarket": "{country} được cấu hình cho địa lý, tiền tệ, thuật ngữ và bản đồ địa phương. Kết nối dữ liệu niêm yết địa phương để xem nguồn cung.", "explore.askAi": "Hỏi trợ lý AI", "explore.openMap": "Mở bản đồ đã cấu hình",
    "card.saved": "Đã lưu vào bộ sưu tập", "card.removed": "Đã xóa khỏi mục đã lưu", "card.forSale": "Đang bán", "card.ownerSale": "Chủ nhà bán", "card.forRent": "Cho thuê", "card.ownerLease": "Chủ nhà cho thuê", "card.save": "Lưu bất động sản", "card.lots": "chỗ đậu", "card.minute": "phút", "card.guideRent": "Giá thuê tham khảo", "card.guidePrice": "Giá tham khảo", "card.view": "Xem {title}", "card.perMonth": "/ tháng",
    "map.eyebrow": "Bản đồ thông minh", "map.title": "Khám phá theo bối cảnh.", "map.description": "Nghiêng, phóng to và so sánh nhà ở, tài sản thương mại và bối cảnh địa phương trên khắp {country}.", "map.loading": "Đang tải tài sản trên bản đồ…", "map.mapped": "Đang hiển thị {count} tài sản niêm yết trên bản đồ", "map.empty": "Đã tải hồ sơ bản đồ {country} — kết nối nguồn cung địa phương để thêm tài sản", "map.homes": "Nhà ở", "map.commercial": "Thương mại / công nghiệp", "map.threeD": "Góc nhìn công trình 3D", "map.boundaries": "Ranh giới {region}", "map.transitRadius": "Bán kính thời gian di chuyển {transit}", "map.recenter": "Căn giữa", "map.commute": "Di chuyển", "map.commuteInfo": "Chọn nơi làm việc, trường học, cảng hoặc điểm logistics để cấu hình lộ trình di chuyển địa phương.", "map.footer": "Google Maps · Lớp {region} và {transit} minh họa · Thu nhỏ để gom cụm", "map.closePreview": "Đóng xem trước bất động sản", "map.beds": "phòng ngủ", "map.clear": "m thông thủy", "map.viewProperty": "Xem bất động sản", "map.showPanels": "Hiện bảng", "map.hidePanels": "Ẩn bảng", "map.assets": "tài sản", "map.viewAsset": "Xem {title}", "map.zoomAssets": "Phóng to {count} {properties}",
  }),
  "zh-Hans": withEnglishFallback({
    "nav.buy": "买房", "nav.rent": "租房", "nav.sell": "出售", "nav.rentOut": "出租", "nav.map": "地图智能", "nav.ai": "AI 顾问", "nav.agent": "经纪人门户", "nav.plans": "方案", "nav.search": "搜索房产", "nav.chooseMarket": "选择当前房地产市场", "nav.chooseLanguage": "选择显示语言", "nav.signIn": "登录", "nav.menu": "切换菜单",
    "home.eyebrow": "读懂 {country} 房产", "home.titleLead": "找到真正", "home.titleEmphasis": "适合你的住址。", "home.intro": "通过沉浸式地图、经过验证的背景工具、交易洞察和理解你需求的顾问探索房产。", "home.search": "住宅、{region}、{transit} 或街道", "home.explore": "探索", "home.privacy": "隐私优先洞察", "home.transitDiscovery": "基于 {transit} 的发现", "home.context": "附带说明的背景信息", "home.activeMarket": "当前市场", "home.profileLoaded": "地理与地图配置已加载", "home.featureMap": "3D {region} 地图", "home.featureMapDesc": "探索背景，而不只是图钉", "home.immersive": "沉浸式看房", "home.immersiveDesc": "日间与夜间参观", "home.transaction": "交易视角", "home.transactionDesc": "阅读价格历程", "home.matching": "AI 匹配", "home.matchingDesc": "解释什么适合以及为什么", "home.curated": "精选住宅", "home.homesTitle": "让房子拥有更清晰的故事。", "home.homesDescription": "通过沉浸式视图、产权背景以及透明的重点与关注事项记录，超越表面细节。", "home.viewAll": "查看全部房产", "home.catalogReady": "{country} 已可接入本地房源目录。", "home.catalogDescription": "地图、货币、区域分类和房产术语均已配置。连接本地房源数据即可发布市场专属库存。", "home.spatial": "空间智能", "home.seeAddress": "看见完整的地址。", "home.seeAddressDesc": "在一个视图中查看建筑形态、本地背景、交通半径和街区边界。", "home.spatialTitle": "{country}，围绕你的优先事项呈现。", "home.spatialDescription": "切换至 3D 视角，查看附近交通，对比 {region} 边界，并从街区尺度深入到房源细节而不丢失背景。", "home.buildingFootprints": "3D 建筑轮廓", "home.transitRadii": "{transit} 出行时间半径", "home.regionOverlays": "{region} 边界图层", "home.clusteredSignals": "聚合房产信号", "home.openMap": "打开地图智能", "home.conciergeTitle": "告诉我们你想如何生活。我们会把它转化为合适的地点。", "home.conciergeDescription": "买家和租客顾问会综合通勤、预算、产权期限、空间和生活方式。", "home.meetConcierge": "认识你的 AI 顾问", "home.platform": "可配置的 {country} 房产智能平台。", "home.privacyDesign": "隐私保护设计", "home.demoData": "精选演示数据", "home.verify": "需要独立核实",
    "explore.discover": "探索 {country}", "explore.title": "在背景中看见房产。", "explore.onMap": "在地图上探索", "explore.search": "搜索地址、{transit} 或 {region}", "explore.listingMode": "挂牌方式", "explore.allRegions": "全部{region}", "explore.allTypes": "全部类型", "explore.propertyType": "房产类型", "explore.anyOwnership": "不限产权", "explore.minArea": "最小建筑面积", "explore.anySize": "不限面积", "explore.anyTravel": "不限 {transit} 出行时间", "explore.within": "{minutes} 分钟内", "explore.commercial": "商业运营", "explore.commercialDescription": "按预定用途和物理条件进一步筛选。", "explore.anyUsage": "不限用途", "explore.anyLoading": "不限荷载", "explore.anyHeight": "不限层高", "explore.matched": "套匹配房产", "explore.anyPrice": "不限价格", "explore.upTo": "最高 {price}", "explore.resultsInfo": "结果目前按背景匹配度排序。", "explore.noExact": "暂未找到完全匹配的结果", "explore.emptySingapore": "试着放宽筛选条件，或请 AI 顾问根据你的优先事项进行分析。", "explore.emptyMarket": "{country} 已配置本地地理、货币、术语和地图。连接本地房源数据以查看库存。", "explore.askAi": "咨询 AI 顾问", "explore.openMap": "打开已配置地图",
    "card.saved": "已保存到你的收藏", "card.removed": "已从收藏房产中移除", "card.forSale": "待售", "card.ownerSale": "业主出售", "card.forRent": "待租", "card.ownerLease": "业主出租", "card.save": "收藏房产", "card.lots": "车位", "card.minute": "分钟", "card.guideRent": "参考租金", "card.guidePrice": "参考价格", "card.view": "查看 {title}", "card.perMonth": "/ 月",
    "map.eyebrow": "地图智能", "map.title": "按背景探索。", "map.description": "倾斜、缩放并比较 {country} 各地的住宅、商业资产和本地背景。", "map.loading": "正在加载地图资产…", "map.mapped": "当前已映射 {count} 套挂牌资产", "map.empty": "{country} 地图配置已加载——连接本地库存即可添加资产", "map.homes": "住宅", "map.commercial": "商业 / 工业", "map.threeD": "3D 建筑视角", "map.boundaries": "{region} 边界", "map.transitRadius": "{transit} 出行时间半径", "map.recenter": "重新居中", "map.commute": "通勤", "map.commuteInfo": "选择工作地点、学校、港口或物流节点以配置本地通勤路线。", "map.footer": "Google 地图 · 示意性 {region} 和 {transit} 图层 · 缩小以聚合", "map.closePreview": "关闭房产预览", "map.beds": "卧室", "map.clear": "米净高", "map.viewProperty": "查看房产", "map.showPanels": "显示面板", "map.hidePanels": "隐藏面板", "map.assets": "资产", "map.viewAsset": "查看 {title}", "map.zoomAssets": "缩放至 {count} 套{properties}",
  }),
};

export const translationKeys = Object.keys(englishMessages) as TranslationKey[];

export const mapFallbackMessages = {
  en: { unavailable: "Google Maps is temporarily unavailable", detail: "The map can retry without leaving this page.", retry: "Retry map" },
  id: { unavailable: "Google Maps sementara tidak tersedia", detail: "Peta dapat dicoba lagi tanpa meninggalkan halaman ini.", retry: "Coba lagi" },
  ms: { unavailable: "Google Maps tidak tersedia buat sementara waktu", detail: "Peta boleh dicuba semula tanpa meninggalkan halaman ini.", retry: "Cuba semula" },
  th: { unavailable: "Google Maps ใช้งานไม่ได้ชั่วคราว", detail: "สามารถลองโหลดแผนที่อีกครั้งได้โดยไม่ต้องออกจากหน้านี้", retry: "ลองอีกครั้ง" },
  vi: { unavailable: "Google Maps tạm thời không khả dụng", detail: "Bạn có thể thử lại bản đồ mà không cần rời khỏi trang này.", retry: "Thử lại" },
  "zh-Hans": { unavailable: "Google 地图暂时不可用", detail: "无需离开此页面即可重试地图。", retry: "重试地图" },
} satisfies Record<LocaleId, { unavailable: string; detail: string; retry: string }>;

export function getMapFallbackMessages(localeId: LocaleId) {
  return mapFallbackMessages[localeId];
}

export function getLocaleConfig(localeId?: string | null): LocaleConfig {
  return localeId && localeId in localeConfigs ? localeConfigs[localeId as LocaleId] : localeConfigs[defaultLocaleId];
}

export function translate(localeId: LocaleId, key: TranslationKey, values: TranslationValues = {}): string {
  const message = translationDictionaries[localeId]?.[key] ?? englishMessages[key];
  return message.replace(/\{(\w+)\}/g, (_match, name: string) => String(values[name] ?? `{${name}}`));
}
