import type { Property } from "@shared/propertyData";

type FloorPlan = NonNullable<Property["floorPlan"]>;

export function FloorPlanPreview({ floorPlan, title }: { floorPlan: FloorPlan; title: string }) {
  const rooms = Math.max(1, Math.min(4, floorPlan.bedrooms || 1));
  if (floorPlan.imageUrl) {
    return <figure className="overflow-hidden rounded-2xl border border-[#17382f]/10 bg-white"><img src={floorPlan.imageUrl} alt={`${title}: ${floorPlan.label}`} className="aspect-[16/10] w-full bg-[#fbfaf6] object-contain" /><figcaption className="border-t border-[#17382f]/8 px-4 py-3 text-xs leading-5 text-[#647b74]"><strong className="font-semibold text-[#17382f]">{floorPlan.label}</strong><br />{floorPlan.note}</figcaption></figure>;
  }
  return <figure className="overflow-hidden rounded-2xl border border-[#17382f]/10 bg-[#fbfaf6]"><div className="p-4 sm:p-6"><svg viewBox="0 0 640 380" role="img" aria-label={`${title}: ${floorPlan.label}`} className="h-auto w-full"><rect x="20" y="20" width="600" height="340" rx="12" fill="#fdfcf7" stroke="#17382f" strokeWidth="4" /><rect x="42" y="42" width="255" height="174" rx="4" fill="#e7eee8" stroke="#55746b" strokeWidth="3" /><text x="170" y="136" textAnchor="middle" fill="#17382f" fontSize="18" fontFamily="DM Sans, sans-serif" fontWeight="700">Living / dining</text><rect x="318" y="42" width="280" height="82" rx="4" fill="#f4ebda" stroke="#8f6b3c" strokeWidth="3" /><text x="458" y="88" textAnchor="middle" fill="#573b18" fontSize="16" fontFamily="DM Sans, sans-serif" fontWeight="700">Kitchen</text><rect x="318" y="145" width="280" height="71" rx="4" fill="#e9f0ef" stroke="#55746b" strokeWidth="3" /><text x="458" y="187" textAnchor="middle" fill="#17382f" fontSize="15" fontFamily="DM Sans, sans-serif" fontWeight="700">Utility / bath</text>{Array.from({ length: rooms }).map((_, index) => { const width = 556 / rooms; const x = 42 + index * width; return <g key={index}><rect x={x} y="238" width={width - 7} height="100" rx="4" fill={index === 0 ? "#e8eee9" : "#f3f1e8"} stroke="#55746b" strokeWidth="3" /><text x={x + (width - 7) / 2} y="294" textAnchor="middle" fill="#17382f" fontSize="14" fontFamily="DM Sans, sans-serif" fontWeight="700">{index === 0 ? "Primary room" : `Room ${index + 1}`}</text></g>; })}</svg></div><figcaption className="border-t border-[#17382f]/8 bg-white px-4 py-3 text-xs leading-5 text-[#647b74]"><strong className="font-semibold text-[#17382f]">{floorPlan.label}</strong><br />{floorPlan.note}</figcaption></figure>;
}
