import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import type { Property } from "@shared/propertyData";
import { AlertTriangle, BadgeCheck, Building2, FileSearch, LockKeyhole, MessageSquareText, Minus, ShieldCheck, TrendingUp, UserRoundCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

export function PropertyIntelligence({ property, disclaimer }: { property: Property; disclaimer: string }) {
  const { isAuthenticated } = useAuth();
  const [message, setMessage] = useState(`I am interested in ${property.title}. Please share viewing availability and any key documents for review.`);
  const enquiry = trpc.enquiry.create.useMutation({ onSuccess: () => { toast.success("Enquiry sent securely"); setMessage(""); }, onError: error => toast.error(error.message) });
  const trendData = useMemo(() => [...property.transactions].reverse().map(item => ({ year: new Date(item.date).getFullYear().toString(), psf: item.psf, type: item.type, price: item.price })), [property.transactions]);
  const sales = property.transactions.filter(item => item.type === "Sale");
  const latestSale = sales[0];
  const earliestSale = sales[sales.length - 1];
  const appreciation = latestSale && earliestSale ? Math.round(((latestSale.psf - earliestSale.psf) / earliestSale.psf) * 100) : 0;
  const incidentStyle = { positive: { icon: BadgeCheck, bg: "bg-[#e5f1e9]", text: "text-[#28634b]", label: "Positive context" }, neutral: { icon: Minus, bg: "bg-[#eeeadd]", text: "text-[#7c684a]", label: "Estate record" }, negative: { icon: AlertTriangle, bg: "bg-[#f4e7e2]", text: "text-[#945440]", label: "Reported concern" } } as const;
  return <section id="intelligence" className="border-t border-[#17382f]/10 bg-[#f7f6f1] py-20"><div className="container">
    <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Property intelligence</p><h2 className="mt-3 max-w-2xl font-display text-4xl sm:text-5xl">More context. Better questions.</h2></div><p className="max-w-lg text-sm leading-7 text-[#647b74]">A structured view of curated estate records, anonymized ownership context, and demonstration transaction history. Sensitive information is never presented as verified fact.</p></div>
    <div className="mt-10 grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
      <div className="rounded-[28px] bg-white p-6 shadow-[0_18px_65px_rgba(23,56,47,.06)] sm:p-8"><div className="flex items-center justify-between"><div><p className="eyebrow">Unit & estate history</p><h3 className="mt-2 font-display text-2xl">Curated record timeline</h3></div><span className="grid size-11 place-items-center rounded-full bg-[#edf1ed] text-[#275649]"><FileSearch className="size-5" /></span></div><div className="mt-7 grid gap-3">{property.incidents.map(incident => { const style = incidentStyle[incident.category]; const Icon = style.icon; return <article key={`${incident.year}-${incident.title}`} className="grid gap-4 rounded-2xl border border-[#17382f]/8 bg-[#faf9f5] p-4 sm:grid-cols-[72px_1fr]"><div><p className="text-sm font-bold text-[#17382f]">{incident.year}</p><span className={`mt-2 inline-flex size-8 items-center justify-center rounded-full ${style.bg} ${style.text}`}><Icon className="size-4" /></span></div><div><p className={`text-[10px] font-bold uppercase tracking-[.14em] ${style.text}`}>{style.label}</p><h4 className="mt-1.5 text-sm font-semibold">{incident.title}</h4><p className="mt-2 text-xs leading-5 text-[#647b74]">{incident.detail}</p><p className="mt-2 text-[10px] font-semibold text-[#9aaaa5]">Source: {incident.source}</p></div></article>; })}</div>
        <div className="mt-5 flex gap-3 rounded-2xl border border-[#c89a59]/25 bg-[#fbf5e9] p-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#a27035]" /><div><p className="text-xs font-bold text-[#785b35]">Important verification disclaimer</p><p className="mt-2 text-[11px] leading-5 text-[#7b6b52]">{disclaimer}</p></div></div>
      </div>
      <div className="grid gap-6"><div className="rounded-[28px] bg-[#17382f] p-7 text-white shadow-[0_18px_65px_rgba(23,56,47,.17)]"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d5ae72]">Privacy-safe owner context</p><h3 className="mt-3 font-display text-2xl">Current ownership</h3></div><LockKeyhole className="size-5 text-[#d5ae72]" /></div><div className="mt-8 flex items-center gap-4"><span className="grid size-16 place-items-center rounded-full border border-white/15 bg-white/8 font-display text-2xl text-[#d5ae72]">{property.owner.initials}</span><div><p className="text-sm font-semibold">Anonymized owner</p><p className="mt-1 text-xs text-white/55">Identity and contact details withheld</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">{property.owner.ownershipYears}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/50">Years held</p></div><div className="rounded-2xl bg-white/7 p-4"><p className="text-2xl font-semibold">{property.owner.propertyCount}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-white/50">Properties owned</p></div></div><div className="mt-5 flex gap-2 border-t border-white/10 pt-4 text-[10px] leading-4 text-white/50"><ShieldCheck className="size-4 shrink-0 text-[#d5ae72]" />Only initials, duration, and property count are displayed. No identity inference is permitted.</div></div>
        <div className="rounded-[28px] border border-[#17382f]/10 bg-white p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e7eee9] text-[#275649]"><UserRoundCheck className="size-5" /></span><div><p className="text-sm font-semibold">Verified privacy controls</p><p className="mt-1 text-xs text-[#71857f]">Sensitive fields are excluded at the API layer.</p></div></div></div></div>
    </div>
    <div className="mt-6 rounded-[28px] bg-white p-6 shadow-[0_18px_65px_rgba(23,56,47,.06)] sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><p className="eyebrow">Transaction intelligence</p><h3 className="mt-2 font-display text-3xl">Unit and nearby price history</h3></div><div className="flex gap-3"><div className="rounded-2xl bg-[#eef2ee] px-4 py-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[#71857f]">Latest sale PSF</p><p className="mt-1 text-lg font-semibold">S${latestSale?.psf.toLocaleString()}</p></div><div className="rounded-2xl bg-[#eef2ee] px-4 py-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[#71857f]">Recorded trend</p><p className="mt-1 flex items-center gap-1 text-lg font-semibold text-[#28634b]"><TrendingUp className="size-4" />{appreciation}%</p></div></div></div>
      <div className="mt-8 grid gap-7 xl:grid-cols-[.8fr_1.2fr]"><div className="h-[280px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ top: 12, right: 10, left: -18, bottom: 0 }}><defs><linearGradient id="psfFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2f7765" stopOpacity={0.3}/><stop offset="95%" stopColor="#2f7765" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#dce4de" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="year" axisLine={false} tickLine={false} tick={{ fill: "#71857f", fontSize: 10 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#71857f", fontSize: 10 }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #dce4de", fontSize: 11 }} formatter={(value: number) => [`S$${value.toLocaleString()}`, "PSF"]} /><Area type="monotone" dataKey="psf" stroke="#2f7765" strokeWidth={2.5} fill="url(#psfFill)" /></AreaChart></ResponsiveContainer></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-[#17382f]/10 text-[9px] font-bold uppercase tracking-[.14em] text-[#869791]"><th className="pb-3">Date</th><th className="pb-3">Property / Unit</th><th className="pb-3">Type</th><th className="pb-3 text-right">Price</th><th className="pb-3 text-right">PSF</th></tr></thead><tbody>{property.transactions.map(item => <tr key={`${item.date}-${item.unit}`} className="border-b border-[#17382f]/7 text-xs"><td className="py-4 text-[#647b74]">{new Date(item.date).toLocaleDateString("en-SG", { month: "short", year: "numeric" })}</td><td className="py-4"><p className="font-semibold">{item.property}</p><p className="mt-1 text-[10px] text-[#8a9a95]">{item.unit}</p></td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${item.type === "Sale" ? "bg-[#e4efe8] text-[#28634b]" : "bg-[#eee9dd] text-[#806b4e]"}`}>{item.type}</span></td><td className="py-4 text-right font-semibold">{item.type === "Rent" ? `S$${item.price.toLocaleString()}/mo` : `S$${(item.price / 1_000_000).toFixed(2)}M`}</td><td className="py-4 text-right text-[#647b74]">S${item.psf.toLocaleString()}</td></tr>)}</tbody></table></div></div><p className="mt-5 text-[10px] leading-5 text-[#93a19d]">Demonstration transaction records are included to illustrate analytical presentation. Verify current and historical records through official Singapore transaction sources before reliance.</p>
    </div>
    <div className="mt-6 grid gap-6 rounded-[28px] bg-[#e6ece7] p-6 sm:p-8 lg:grid-cols-[.7fr_1.3fr]"><div><span className="grid size-11 place-items-center rounded-full bg-[#17382f] text-[#d5ae72]"><MessageSquareText className="size-5" /></span><h3 className="mt-5 font-display text-3xl">Ask about this {property.isCommercial ? "asset" : "home"}.</h3><p className="mt-3 text-sm leading-6 text-[#647b74]">Send a structured enquiry without exposing the owner's personal information.</p></div><form onSubmit={event => { event.preventDefault(); if (!isAuthenticated) return startLogin(); enquiry.mutate({ propertyId: property.id, message }); }} className="rounded-2xl bg-white p-4"><textarea required minLength={10} value={message} onChange={event => setMessage(event.target.value)} className="min-h-28 w-full resize-none bg-transparent text-sm leading-6 outline-none" placeholder="What would you like to know?" /><div className="flex items-center justify-between border-t border-[#17382f]/8 pt-3"><p className="text-[10px] text-[#8a9a95]">Sent securely to the listing workspace</p><Button disabled={enquiry.isPending} className="rounded-full bg-[#17382f]">{enquiry.isPending ? "Sending…" : "Send enquiry"}</Button></div></form></div>
  </div></section>;
}
